### ISSUE TITLE
Redusere VM size for aks-noder i Apps cluster

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#10]
Altinn orgs gruppen brukte i januar ca 60K på virtuelle maskiner.
Halvparten av de 60 går til VM utgifter tilknyttet 16 AKS klustre for reelle tjenesteeiere i tt02.
På disse har det vist seg å være meget lite trafikk på kveldstid, og for mange av de også meget begrenset trafikk på dagtid.
En behovsbasert dynamisk nedskalering ansess og prioriteres derfor som et godt taktisk og kostnadsreduserende tiltak.
En forventet betydelig økning i antall av slike klustre (i forbindelse med utbredelsesprosjektet) aktualiserer optimalisering av VMbruk ytterligere.

https://dev.azure.com/digdir/Altinn/_workitems/edit/50787

- [x] Endre node type apps cluster PROD
- [ ] #68

**Comment by Herskis** [comment]
Inntil videre har vi en liten utfordring med oppfølging her, siden vi nå mangler tilgang til CostManagement inntil overgangen fra ATEA til CRAYON som lisenspartner er utført.

**Comment by bengtfredh** [comment]
Closing comment: Changed node type in all clusters.
