### ISSUE TITLE
Sjekke hvem som benytter t30-gitea-db

### ISSUE THREAD

**Issue by Herskis** [Altinn/altinn-platform#1007]
Monitorere, eventuelt stoppe denne databasen for å se om den er i bruk.

Avklare dette med @RonnyB71 og @nkylstad

**Comment by nkylstad** [comment]
@mirkoSekulic kan kanskje svare på om dette er noe studio bruker

**Comment by mirkoSekulic** [comment]
@nkylstad Vi bruker ikke denne database fra studio.

**Comment by nkylstad** [comment]
Da mistenker jeg at dere fint kan stoppe den og se om noe skjer @Herskis. Meg bekjent er det kun Studio som bruker Gitea.

**Comment by Herskis** [comment]
DB er nå slettet
