### ISSUE TITLE
Flytte Altinncdn DNS fra Tjenester 3.0 subscription

### ISSUE THREAD

**Issue by Herskis** [Altinn/altinn-platform#1009]
Vurdere om alle DNS soner skal samles i en felles subscription

**Comment by Herskis** [comment]
Etter rydding av Tjenester 3.0 Subscription er mitt forslag at vi renamer denne til Altinn-CDN

**Comment by Herskis** [comment]
@tjololo Vudere om denne kanskje kan bli liggende der den er, siden Altinn CDN beholder sub´en når alt annet er ryddet bort?

**Comment by tjololo** [comment]
> @tjololo Vudere om denne kanskje kan bli liggende der den er, siden Altinn CDN beholder sub´en når alt annet er ryddet bort?

Høres ut som en grei løsning for han som ellers må flytte cdn😅😂
