### ISSUE TITLE
Access to OED Production environment

### ISSUE THREAD

**Issue by kurt70** [Altinn/altinn-platform#1027]
### Toil type

None

### Context for the task

The OED team should at least have contributor access to det resources in the "altinn-digdir-oed-rg" rgroup.

- [x] daniel.rustad.johansen@digdir.no
- [x] lars.olav.kjolstad@digdir.no
- [x] thomas.ostdahl@digdir.no
- [x] kurt.monge@digdir.no

**Comment by Herskis** [comment]
Har opprettet brukergruppe, men her må det også opprettes prod-brukere

**Comment by Herskis** [comment]
Opprettet gruppen:
DIGDIR-OEDapp-Prod-Developers og lagt inn som contributor for resourcegroup, samt lagt inn prodbrukere som er blitt sendt ut.
Opprettet også for test med de normale brukerne
DIGDIR-OEDapp-Test-Developers

Vi har gjort en vurdering på om Contributor var en for priviligert rolle, men per dags dato er det ingen RBAC roller som gir tilstrekkelig tilgang for drift av functionapps
