### ISSUE TITLE
Lacking documentation on events & subscriptions

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-platform#103]
## Description
The documentation available on events and subscriptions is not clear enough for the application owners.
Should be clearified and/or re-written with the end user in focus. 

## Considerations
Placement of doc

## Specification
Swagger has been enhanced with examples for all requests ands schemas. 
If more documentation is required we should consider moving [this section](https://docs.altinn.studio/technology/architecture/components/application/solution/altinn-platform/events/) to somewhere more available on docs

## Development tasks
- [x] Improve swagger doc
- [x] Document flow for registering event subscriptions 
- [x] Document examples of querying events. Format of _time_, _from_. 
- [x] QA
- [x] Update swagger in all relevant places
- [x] Document pattern used to enrich swagger in developer handbook

**Comment by TheTechArch** [comment]
I guess this is duplicate https://github.com/Altinn/altinn-studio/issues/7382
