### ISSUE TITLE
Add profile PostgreSQL server CNAME records for TT02 and PROD

### ISSUE THREAD

**Issue by simon-ellefsen** [Altinn/altinn-platform#1040]
Add CNAME records for the Profile postgreSQL servers in TT02 and PROD. Should follow the same naming standard as the other profile servers.

Name: tt02-profile-postgres
Value: altinn-profile-db-tt02-pgflex.postgres.database.azure.com

Name: prod-profile-postgres
Value: altinn-profile-db-prod-pgflex.postgres.database.azure.com

- [x] TT02 CNAME record created
- [x] PROD CNAME record created

**Comment by Herskis** [comment]
Da er disse på plass:![Image](https://github.com/user-attachments/assets/a502e1ed-2414-4dd8-8a2a-3f511f9953bb)
