### ISSUE TITLE
Div Credential SPR-AzDevOps is expiring at 28.11.2024!

### ISSUE THREAD

**Issue by annerisbakk** [Altinn/altinn-platform#1079]
- [x] Credential SPR-AzDevOps-AltOrgTestMG(65a6d6e0-722a-42f4-b522-4609fdf35043) is expiring at 28.11.2024!
- [x] Credential SPR-AzDevOps-AltPlatformReg(30f21c51-fc09-4d95-abb7-4adfa91e2136) is expiring at 28.11.2024!
- [x] Credential SPR-AzDevOps-AltOrgProdMG(be1ed816-5fea-4838-9a4e-01168ead1014) is expiring at 28.11.2024!

https://pedia.altinn.cloud/altinn-3/ops/certificate/routines/#liste-over-service-principals-som-benyttes-i-azure-devops

Credentials som er slettet da de mest sannsynlig ikke er i bruk lengre:
- Credential SPR-AzDevOps-AltStudioProd(df061dae-32b0-4d65-ab8a-b565f240d172) is expiring at 28.11.2024!
- Credential SPR-AzDevOps-AltStudioReg(017d5e2a-affc-4949-8739-d705fc84a367) is expiring at 28.11.2024!

**Comment by annerisbakk** [comment]
@Herskis Hvilket repo bør sertikatsaker ligge i

**Comment by tjololo** [comment]
Oppdatert de som er i bruk og slettet credentials som er på tur å gå ut for de som ikke lenger benyttes. Hvis ingenting begynner å feile kan disse appene/service principals slettes
