### ISSUE TITLE
Access rights to Kubernetes services in production.

### ISSUE THREAD

**Issue by Ahmed-Ghanam** [Altinn/altinn-platform#1108]
Hi.

Please assign my account (acn-aghan-prod@ai-dev.no) access rights to Kubernetes services in the production environment. Thank you!

**Comment by Herskis** [comment]
I need this specified a whole lot more, I have sent @SandGrainOne a PM so that the Core Team can clearify!

**Comment by Herskis** [comment]
I have fixed this now, but there are some issues we have to look at concerning security vs. the ability to demand production access.
