### ISSUE TITLE
Set TTL on apps cluster A records down to 5 min

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#1135]
### Toil type

None

### Context for the task

When we recreate cluster all dns records need to be updated. Looks like our dns provider allow 5 min as lowest value. We need to prepare for migration by lowering TTL to lowest possible. The gui is very unstable - I think we need to check if we can get the provider to update all our records in backend.

### TT02

- [x] brg.apps.tt02.altinn.no
- [x] buf.apps.tt02.altinn.no
- [x] dat.apps.tt02.altinn.no
- [x] dibk.apps.tt02.altinn.no
- [x] digdir.apps.tt02.altinn.no
- [x] dihe.apps.tt02.altinn.no
- [x] dmf.apps.tt02.altinn.no
- [x] dsb.apps.tt02.altinn.no
- [x] fd.apps.tt02.altinn.no
- [x] fhi.apps.tt02.altinn.no
- [x] fors.apps.tt02.altinn.no
- [x] gk.apps.tt02.altinn.no
- [x] hdir.apps.tt02.altinn.no
- [x] hemit.apps.tt02.altinn.no
- [x] hemit.apps.tt02.altinn.no
- [x] hi.apps.tt02.altinn.no
- [x] hmrhf.apps.tt02.altinn.no
- [x] indi.apps.tt02.altinn.no
- [x] k1103.apps.tt02.altinn.no
- [x] krt.apps.tt02.altinn.no
- [x] kv.apps.tt02.altinn.no
- [x] kyv.apps.tt02.altinn.no
- [x] lt.apps.tt02.altinn.no
- [x] lts.apps.tt02.altinn.no
- [x] mat.apps.tt02.altinn.no
- [x] mdir.apps.tt02.altinn.no
- [x] nav.apps.tt02.altinn.no
- [x] nb.apps.tt02.altinn.no
- [x] nbib.apps.tt02.altinn.no
- [x] nhn.apps.tt02.altinn.no
- [x] nkom.apps.tt02.altinn.no
- [x] nkr.apps.tt02.altinn.no
- [x] npe.apps.tt02.altinn.no
- [x] nsm.apps.tt02.altinn.no
- [x] nve.apps.tt02.altinn.no
- [x] oed.apps.tt02.altinn.no
- [x] ok.apps.tt02.altinn.no
- [x] oko.apps.tt02.altinn.no
- [x] pat.apps.tt02.altinn.no
- [x] sfd.apps.tt02.altinn.no
- [x] sfvt.apps.tt02.altinn.no
- [x] skd.apps.tt02.altinn.no
- [x] slv.apps.tt02.altinn.no
- [x] spk.apps.tt02.altinn.no
- [x] srf.apps.tt02.altinn.no
- [x] ssb.apps.tt02.altinn.no
- [x] staf.apps.tt02.altinn.no
- [x] stami.apps.tt02.altinn.no
- [x] svv.apps.tt02.altinn.no
- [x] tad.apps.tt02.altinn.no
- [x] tra.apps.tt02.altinn.no
- [x] ttd.apps.tt02.altinn.no
- [x] udi.apps.tt02.altinn.no
- [x] udir.apps.tt02.altinn.no
- [x] valg.apps.tt02.altinn.no
- [x] vigo.apps.tt02.altinn.no

### PROD

- [x] brg.apps.altinn.no
- [x] dat.apps.altinn.no
- [x] dibk.apps.altinn.no
- [x] dig.apps.altinn.no
- [x] digdir.apps.altinn.no
- [x] dihe.apps.altinn.no
- [x] dmf.apps.altinn.no
- [x] dsb.apps.altinn.no
- [x] fd.apps.altinn.no
- [x] fhi.apps.altinn.no
- [x] gk.apps.altinn.no
- [x] hemit.apps.altinn.no
- [x] hemit.apps.altinn.no
- [x] hi.apps.altinn.no
- [x] hmrhf.apps.altinn.no
- [x] krt.apps.altinn.no
- [x] kv.apps.altinn.no
- [x] kyv.apps.altinn.no
- [x] lt.apps.altinn.no
- [x] mat.apps.altinn.no
- [x] nb.apps.altinn.no
- [x] nbib.apps.altinn.no
- [x] nkom.apps.altinn.no
- [x] oed.apps.altinn.no
- [x] pat.apps.altinn.no
- [x] sfvt.apps.altinn.no
- [x] skd.apps.altinn.no
- [x] slv.apps.altinn.no
- [x] srf.apps.altinn.no
- [x] ssb.apps.altinn.no
- [x] stami.apps.altinn.no
- [x] svv.apps.altinn.no
- [x] tad.apps.altinn.no
- [x] ttd.apps.altinn.no
- [x] udi.apps.altinn.no
- [x] udir.apps.altinn.no
- [x] valg.apps.altinn.no

**Comment by Herskis** [comment]
@bengtfredh Da er alle records for tt02 satt, fortsetter med å klargjøre produksjon

**Comment by Herskis** [comment]
@bengtfredh og da er alle satt til 5 minutter
