### ISSUE TITLE
K6 script output testresultat styres til lagringslokasjon/måldatabase.

### ISSUE THREAD

**Issue by borgethommesen** [Altinn/altinn-platform#115]
Connection details like username and password is stored in a KeyVault.

Alternatives:
- k6 are be able to access the key vault to publis results to the database.
- Secrets in the Azyre DevOps pipline

**Comment by bengtfredh** [comment]
Vi må finne ut hvilke ip k6 tester kjører på slik at vi kan sette opp nettverk og brannmur for at k6 kan koble seg til.
