### ISSUE TITLE
Reporting of performance test for analysis. Additional tasks.

### ISSUE THREAD

**Issue by annerisbakk** [Altinn/altinn-platform#144]
- [x] Legge til Grafana rapporteringsfunksjonalitet til de øvrige ytelsestestene https://dev.azure.com/brreg/altinn-studio/_build?_a=allDefinitions&path=%5Cload-test%5C

- [x] Load-test-k6-rf0002
- [x] Load-test-k6-download-rf0002
- [x] Load-test-k6-orchestration
- [x] Load-test-k6-rf0002-with-attachment
- [x] Load-test-k6-memo
- [x] Load-test-k6-rf0002-portal-simulation
- [x] Load-test-k6-sbl
- [x] load-test-k6-sirius
- [x] load-test-poll-get-instances
- [x] load-testing-cleanup
- [x] blue-green-test

- [x] Robustifisere ytelsesscript for å kunne kjøre på andre miljøer der rapporteringsfunksjonalitet ikke skal benyttes.

**Comment by borgethommesen** [comment]
- [ ] Legge til Grafana rapporteringsfunksjonalitet til de øvrige ytelsestestene https://dev.azure.com/brreg/altinn-studio/_build?_a=allDefinitions&path=%5Cload-test%5C

- [ ] Justere Dashboard for å rapportere relevant informasjon

- [ ] Robustifisere ytelsesscript for å kunne kjøre på andre miljøer der rapporteringsfunksjonalitet ikke skal benyttes.
