### ISSUE TITLE
Release not showing up for traefik after moving from demonsets to deployments

### ISSUE THREAD

**Issue by RonnyB71** [Altinn/altinn-platform#150]
### Description of the bug

When querying the kuberneteswrapper for deployments the object for traefik doesn't include a relase name.

### Steps To Reproduce

1. Navigate to https://dat.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
2. Observe the following result:

`[{"version":"2.7.0","release":null},{"version":"1.1.2","release":"dat-aarligmelding-bemanning"},{"version":"1.1.5","release":"dat-asbest-soknad"},{"version":"2.1.6","release":"dat-bemanningsforetak"},{"version":"0.4.0","release":"dat-bilpleie-soknad"},{"version":"1.3.4","release":"dat-innkvartering"},{"version":"0.0.8","release":"dat-test-prosess"},{"version":"433695","release":"kuberneteswrapper"}]`

3. Note the `{"version":"2.7.0","release":null}` object which represents traefik, this should include a name for the release.

### Cause / Resolution 
Name is retrieved from the helm deployment. Deployment definition for traefik should be updated to match the expected setup for deployments as we have for apps. Implementation in kuberneteswrapper should point in the direction of what is missing.

**Comment by bengtfredh** [comment]
It is not related to change from daemonset to deployment.
More likely related to new helm chart, and config left out on migration.

**Comment by bengtfredh** [comment]
Resolved in PR:
https://dev.azure.com/brreg/altinn-apps-ops/_git/terraform-modules/pullrequest/458
