### ISSUE TITLE
Set up and verify app cluster for GK - Gjenopptakelseskommisjonen (Prod)

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#169]
Description
Set up app cluster for GK Prod

Infrastructure tasks
- [x] Prepare pipeline for GK prod
- [x] Run pipeline for GK prod
- [x] Create and add access token certificate
- [x] Add dns record for GK cluster  @Herskis 
- [x] Order reserved nodes for cluster @Herskis 
- [x] Add link to dashboard in vakt template
 
Acceptance criteria
- [ ] An application is successfully instantiated and submitted.
- [ ] Instance is successfully cleaned up: guid 

Development tasks
- [x] Give GK rights to deploy to Prod on cdn
- [x] Create and deploy app to GK for GK 
- [ ] Notfify that cluster is ready in slack
- [x] Create scopes in Maskinporten @SandGrainOne 
- [x] Clean up testdata.
  - [x] Complete confirm+ hard delete instance
  - [x] Delete deployment + resources from cluster
  - [x] Delete repository from gitea

**Comment by SandGrainOne** [comment]
Har nå 
- verifisert at man kan deploye en app til produksjon for GK.
- instansiert app, bekreftet og slettet.
