### ISSUE TITLE
Backup av data i ny autorisasjonskomponent

### ISSUE THREAD

**Issue by OddArneSaetervik** [Altinn/altinn-platform#172]
### Description

Ifm innføring av delegering av apps er det introdusert nye infrastrukturkomponenter i Altinn3 platform. Dette er
Ny database i PostgreSQL: delegation (med én tabell: delegationChanges)
Ny storage account: storage03 (med én container: delegationpolicies)
Forhold som påvirker backup-behov / strategi:
Storage accounten er satt opp med versioning (ikke snapshots). Endringene i postgre peker på versjoner. Dette gjør at vi har fullstendig historikk over alle delegeringer.
Sletting av delegeringer innebærer at filen i storage accounten blir overskrevet med en tom policy. Blobs blir altså ikke slettet, og soft delete er derfor heller ikke enablet.
Postgre-tabellen tracker endringer til delegerte policies, og brukes av komponenten for å finne riktig policy-fil og version i storage
Siden den lagrer endringer, gjøres kun INSERT og SELECT (ikke DELETE eller UPDATE).
På sikt kan det blir aktuelt å fysisk fjerne oppføringer (f.eks. for slettede enheter/døde personer etter en viss tid, eller historikk utover et visst antall år, sletteforspørsler hjemlet i GDRP etc), men i utgangspunktet ønsker vi å måtte unngå dette.
Gjennomsnittlig radstørrelse (inkl. indekser) er ca 200 bytes, så 100 millioner delegeringsendringer er da ikke mer enn 20GB. Uklart hvor stor en gjennomsnittlig policy-fil er, antagelsen er mellom 1 og 3KB.
På bakgrunn av dette bes det om at egnet backup-strategi utredes og implementeres.

**Comment by annerisbakk** [comment]
@ootneim Denne kan kanskje lukkes da det ivaretas av backup/restore-oppgavene som er under arbeid?

**Comment by ootneim** [comment]
@annerisbakk Ja, denne kan lukkes. ble opprettet lenge før vi virkelig startet på fokus på backup av platform
