### ISSUE TITLE
Tilgangsstyring på Azure DevOps 3.0

### ISSUE THREAD

**Issue by OddArneSaetervik** [Altinn/altinn-platform#173]
### Description

Vi må se litt nærmere på hvordan vi administrerer tilgangen til Azure DevOps: 
Azure DevOps har fått levd fritt. Uten noen formelle rutiner.
Tilganger til repos
Tilganger til pipelines/releases og produksjonssetting
Lisenser - hvilke lisenser kreves
Dekkes ikke av dagens bestillingsrutine

**Comment by Herskis** [comment]
Denne har faktisl blitt løst over tid.

Lisenser er nå knyttet til Azure tenanten, og de som ikke har VS Enterprise lisenser kan få Basic for å se Repoer. Disse lisensene koster ca. 50,- pr. bruker per måned.

Tilganger følger nå tilgangen til Team gruppene som også benyttes av RBAC i Azure.
