### ISSUE TITLE
Enable geo-replikering av tjenesteeiers Container Registry

### ISSUE THREAD

**Issue by OddArneSaetervik** [Altinn/altinn-platform#174]
### Description

Ref [https://digdir-digitalisering.atlassian.net/wiki/spaces/T3KP/pages/5049073/Matrise+for+Backup+og+Restore](https://digdir-digitalisering.atlassian.net/wiki/spaces/T3KP/pages/5049073/Matrise%2Bfor%2BBackup%2Bog%2BRestore)

Geo-replikering (https://docs.microsoft.com/en-us/azure/container-registry/container-registry-geo-replication) er ikke enablet på tjenesteeiers Container Registry. Det bør vurderes på lik linje som andre ressurser som har dette enablet.

**Comment by bengtfredh** [comment]
To enable geo replication of container registry we need to upgrade from Basic to Premium SKU. Basic cost pr day kr1.639 and Premium pr day is kr16.386. So the extra cost altinn3 for this change is for 1 year more than 5mill NOK.

If geo replication is needed we need to review our architecture, if every service owner need their own container registry.

**Comment by annerisbakk** [comment]
@bengtfredh Kan denne lukkes?

**Comment by bengtfredh** [comment]
@annerisbakk I think so - I dont see the cost benefit here
