### ISSUE TITLE
Set up procedure for operators to connect to PostgreSQL server #4999

### ISSUE THREAD

**Issue by OddArneSaetervik** [Altinn/altinn-platform#175]
### Description

As operators we need to be able to connect to the PostgreSQL server to run queries on the database and check data in the tables.

Azure AD should be considered as a way to go.
https://docs.microsoft.com/en-us/azure/postgresql/concepts-aad-authentication

### Tasks

Ref. [User Story 46517](https://dev.azure.com/digdir/Altinn/_workitems/edit/46517): Set up procedure for operators to connect to PostgreSQL server #4999

Setting it up locally: https://docs.altinn.studio/teknologi/altinnstudio/development/handbook/postgres/
Connecting to test or prod env: https://altinnpedia.ai-dev.brreg.no/dev/altinn-studio/postgres/

 Set up procedure where each operator uses their own credentials

### Acceptance Criterias

Team members should be able to connect to the server when required.
Security should be upheld in the solution.

**Comment by tba76** [comment]
Duplicate #12
