### ISSUE TITLE
Upgrade version of Azure API Management DevOps Resource Kit used in CI of API Management

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-platform#176]
## Description
There is a new version of the Azure API Management DevOps Resource Kit tools that we use when creating ARM templates for API Management. We should consider upgrading.

The new version creates files with almost identical content, but the file names are different. This means all scripts and pipelines must be updated.

https://github.com/Azure/azure-api-management-devops-resource-kit/releases

Ops documentation (internal)
https://altinnpedia.ai-dev.brreg.no/ops/release-and-deploy/api-management

## Development tasks
- [ ] Upgrade resource kit version 
- [ ] Identify and fix breaking changes in local scripts
- [ ] Identify and fix breaking changes in deploy pipeline
- [ ] Delete obsolete files 
- [ ] QA
- [ ] Test
- [ ] Redeploy all APIs to all environment to ensure they are all using the latest setup 
- [ ] [Update documentation](https://altinnpedia.ai-dev.brreg.no/ops/release-and-deploy/api-management
)

## Acceptance criteria
- [ ] Documentation reflects latest version of the resource tool kit 
- [ ] It should work as before

**Comment by annerisbakk** [comment]
Terje: Denne lukkes

**Comment by SandGrainOne** [comment]
The tool is no longer activaly maintained. We should look for some other tool or create something for API deploy/update in API Management.
