### ISSUE TITLE
Deploye platform komponenter til resterende platform miljøer (blue/green)

### ISSUE THREAD

**Issue by ootneim** [Altinn/altinn-platform#19]
Oppdater deploy pipeline for å kunne deplyte til AKS platform cluster som er i et blue/green oppsett. Samme oppsett som for AT2X miljøene.

There is a now a new Task Group called "Deploy platform application to all available AKS clusters in environment" that can be used to deploy any of the platform component to any environment. (Except Kuberneteswrapper.)

**Miljøer som skal installeres:**

- [x] YT01
  - [x] Authentication
  - [x] Authorization
  - [x] Events
  - [x] Kuberneteswrapper
  - [x] PDF
  - [x] Profile
  - [x] Receipt
  - [x] Register
  - [x] Storage
- [x] TT02
  - [x] Authentication
  - [x] Authorization
  - [x] Events
  - [x] Kuberneteswrapper
  - [x] PDF
  - [x] Profile
  - [x] Receipt
  - [x] Register
  - [x] Storage
- [x] PROD
  - [x] Authentication
  - [x] Authorization
  - [x] Events
  - [x] Kuberneteswrapper
  - [x] PDF
  - [x] Profile
  - [x] Receipt
  - [x] Register
  - [x] Storage

**Comment by SandGrainOne** [comment]
@ootneim 
Issues attempting to set it up for deploy to TT02:
The KeyVault being used needs to be available for the same service connection being used to update the actual AKS clusters. Right now the KeyVault and the AKS clusters are on different subscriptions.

**Comment by ootneim** [comment]
@SandGrainOne 
Keyvault for Platform tt02 heter "altinn-tt02-kv" og ligger i subscriptionet "Altinn-Platform-Staging"
Hvilken Service Connection er det som skal ha tilgang til Keyvault og AKS cluster?
Så skal jeg sjekke tilgangene.

**Comment by SandGrainOne** [comment]
Release pipelines for all Platform applications have now been updated to deploy applications to the new "blue-green" AKS clusters in all environments.
