### ISSUE TITLE
SKD has issues with unable to search events for org

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-platform#195]
## New description, actions and conclusion

After having worked on this a lot more we've identified the issue to be related to performance when an application owner use the event-search endpoint to identify events after a specified event. The after parameter use the id column which has no index leading to full table scan.

- [x] We have made changes to the database function so it can utilize the size parameter. This gave noticeable improvements in TT02, but was not enough in production.
- [x] We have deleted all events older than 90 days to reduce the amount of data. This improved performance with an unknown amount, but we now see most searches finish at around 30 seconds.
- [X]  SKD has increased their timeout from 30 seconds to 60 seconds giving us more time to produce a response.
- [x] Add an index to the id column. https://github.com/Altinn/altinn-events/issues/85

The final action will be performed through a separate issue. This issue is ready to be closed.

*Previous issue description and work documented below:*

## Description

SKD have issues with querying events
Issue seems to lie in connection to postgresql. 

## Actions

- Change implementation in repository classes to communicate with database asynchronously (deployed to AT 05.08)
- Add events test to the use case tests run in production (05.08)
- Added alert to monitor shutdown of DB in prod (05.08)

### Additional info
```
AzureDiagnostics
| where LogicalServerName_s == "altinn-platform-db-prod-postgres"
| where Category == "PostgreSQLLogs"
| where Message contains "checkpoint starting"
| order by TimeGenerated asc

```

### Analysis

Same pattern for both occurrences. two 500 faults, and then timeouts for all other requests. 
In PostgreSQL logs we can see that a forced shutdown is initiated at the time the fault starts.

![image](https://user-images.githubusercontent.com/47737608/183070018-bab917b9-fd28-4721-a035-83a7c2f46442.png)

Also, "checkpoint starting" occurs more often ( 3 times within seconds) when the fault occurs, rather than every 5 min
No restart of pods during the time of the fault. Error fixes itself somehow. 

#### First occurrence
- Start: 11.07.2022 kl 17.35
- End: 13.07.2022

#### Second occurrence 
- Start: 03.08.2022 kl 17:01
- End: 04.08.2022 kl 14:21

#### Third occurrence
- Start: 10.08.2022 11 ish

No database shutdown ahead of time. Found that the get-events function is the bottle neck and request may take up to 30 sec. We have limited response set to a given size in db, default 50. We want to include an index for the event it. We will be deleting all events older than 90 days .

### Conclusion

The actions below have been taken. We will at this point not be taking any further measures on this issue, but await til the next incident.

- [ ] We have found the triggering reason for the fault, but we have not been able to figure out how to mitigate it.
  - Planned maintenance on the database from Microsoft. Patching. Will occur maximum every 30 days.
- [ ] Monitoring of the triggering reason is in place in all environments, so the team can respond in real time the next time it occurs and also continue debugging. Working theory is that a restart of the pods might solve the issue.
- [ ] Improvements to the communication with the database have been made, but we have not been able to test that this solves the issue. 
- [ ] We have set up notifications for maintenance on the database and will get a warning 72 hours ahead of time to be prepared for the next occurrence
- [ ] We recommend that SKD look into the push events functionality we offer, rather than polling Platform Events.

**Comment by mjulstein** [comment]
The next incident happened, and I don't know what to do.
I am not familiar enough with the Azure Monitor to know what to look for, and what to verify.

**Comment by SandGrainOne** [comment]
Closing again. No new action points from the incident last friday.
