### ISSUE TITLE
Consider if AKS cluster should run with availability zones enabled

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#20]
Our AKS cluster run with availability zones disabled. Which means cluster is tied to 1 physical datacenter. In case of failure in datacenter, cluster and apps will become unavailable. Availability zones has been available in norwayeast since september 2021.

The control plane components such as etcd or the API are spread across the available zones in the region if you define the --zones parameter at cluster creation time. The specific zones which the control plane components are spread across are independent of what explicit zones are selected for the initial node pool.

![image.png](https://images.zenhubusercontent.com/60b4e425c021497a7467adad/be8cfb0d-5456-460f-8d28-6cb281574702)

Benefits:
- We will get higher availability for apps, will still be available after datacenter outage. 

Downside:
- We need to recreate all clusters. There is no options to change to use availability zones for already running cluster.

Cost:
- We will get some egress/ingress traffic cost for replication between zones.

**Comment by ootneim** [comment]
Har enablet dette for platform nå, så ved neste blue/green deployment vil det settes opp i alle 3 zonene.

**Comment by annerisbakk** [comment]
@bengtfredh Hva gjør vi videre med denne?

**Comment by ootneim** [comment]
@annerisbakk @bengtfredh Har en issue for dette i Epic for redundans (og backup)
https://github.com/Altinn/altinn-platform/issues/421

**Comment by annerisbakk** [comment]
@ootneim @bengtfredh Da kan denne lukkes?

**Comment by bengtfredh** [comment]
- #421

**Comment by bengtfredh** [comment]
- #421
