### ISSUE TITLE
Document possible issues with shipment from the eFormidling integration app

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-platform#202]
### Description

We need to document what we are observing and "confront" the eFormidlings-team with questions on how we are supposed to handle the issues.

### Analysis
In general, there are often an explanation for why a shipment fails, but we don't know until after the shipment is attempted. The app only checks that the shipment gets through to the integration point and not further. How do we deal with ensuring that an instance is sent ok whenever a shipment is successfully received by the integration point? 

| Issuetittel | Eksempler | Kommentarer | Endringsansvarlig | Tiltak |
|------|---------|----------------|---------------------------|---------	
| Ikke mulig å sende duplikat av mottaker/avsender/tittel på forsendelse  | Forsendelse med samme mottaker, tittel og avsender og filer er forsøkt sendt mer enn en gang. Forsendelse er derfor avvist.  | - Avsender er alltid Altinn, mottaker vil alltid være begrenset til ett eller flere org nummer, så det er kun tittel vi har spillerom med.  - What if a form will require multiple instances for a single user? - How can we enforce unique titles when the app owner decides? - **What is the wait period before a duplicate combination can be sent?** |-| Kan skyldes dårlig testdata. Ta kontakt med KS dersom dette oppstår med reelle forsendelser |	
| Ingen varsel før endringer i SVarUt/SvarInn (potensielt breaking changes) | 08.06 - Validering feilet (Alle dokumenter kan ikke være ekskludert fra print for en forsendelse som ikke er kun digital) | - Gitt at vi ikke styrer når vi tar inn endringer i KS vil vi kunne få breaking changes i produksjon uten forvarsel. - Kan vi leve med denne risikoen? - Hva gjøres med forsendelser forsøkt sendt i tidsrom mellom endring og evt fiks fra vår side? |-| En endring som har sluppet gjennom her. Det skal ikke være endringer med mindre vi oppgraderer integrasjonspunktet som igjen forholder seg til en versjon av SvarInn / SvarUt. Må sjekke endringsloggen for integrasjonspunkt og også FIKS. Sentralt for alle parter å ikke innføre breakin changes.  |
| Uheldig at alle filtyper som ikke er PDF må ekskluderes fra print |  16.06 - DiHE sender skjema med bilde som vedlegg | Appene våre støtter et bredt spekter med filtyper. Filtyper som skal ekskluderes fra print må legges inn i config under deployment. Ikke holdbart å skulle eksplisitt legge til alle filtyper det kan tenkes at TE åpner opp for. | eFormidling | Steinar tar inn dette som et endringsønske | 
| Navn på vedlegg med norske tegn feiler | "File(s) defined in arkivmelding, but not found in message: æøå.pdf", Couldn't handle æøå in document filename. | Det er opprettet et[ issue i backlog](https://github.com/Altinn/app-template-dotnet/issues/89) for å teste foreslått fremgangsmåte. Men peker til utfordring med ting vi ikke har sett dokumentert noe sted og som våre manuelle tester ikke har fanget opp. Er det flere svakheter som først kommer til lys i produksjon?  | Altinn: fikser encoding i app. |
| Hvordan skjermer vi sluttbruker for våre inner workings når det er så mange fallgruver som en innsending som gjør at den ikke kan sendes via eFormidling?  | DiHE har testet flere innsendinger og tror alt har gått ok pga grønn kvittering i appen, men ved sjekk i integrasjonspunktet ser man feilede forsendelser. | Ønske fra TE: sluttbruker skal ikke trenge å vite om noe sendes via eFormidling eller REST, dvs oppførsel ved innsending skal være uforandret, og det er en forventing om at kvittering kommer med en gang. Vanskelig å få til dette dersom man skal vente på kvittering fra integrasjonspunkt på status.  | Altinn | Det gjøres en analyse på om vi må innføre endringer i appen for å sjekke levert status før kvittering vises til sluttbruker 
| Har vi et reelt behov for printstøtte for appforsendelser? | -  | Dersom det kun er pdf som sendes til print. Gir det mening at en forsendelse som ikke kommer fram til TE heller skal printes? Hva med evt. relevante vedlegg som sluttbruker laster opp? | -|
| Uklare feilmeldinger i loggene. Mangel på forståelse fra vår side?  | Duplikat - Forsendelsesid 29359447-64da-4532-b356-e8f5df3bbcb7 er allerede i bruk. kommer i loggen til integrasjonspunktet. Underliggende feil er at man ikke får generert forsendelsesfil i KS. | -|  Hva fører til denne feilmeldingen? Prøver den å sende forsendelsen flere ganger når en feil oppstår? | Integrasjonspunktet har trolig forsøkt å sende forsendelsen flere ganger.

**Comment by OddArneSaetervik** [comment]
Steinar Henriksen hos eFormidling informerte 08.09.200
No har me publisert versjon 2.8.3 av integrasjonspunktet, med støtte for å lagt til støtte for å ekskludere alle filer bortsett fra PDF fra print ved bruk av KS SvarUt. Det krever ei konfigurasjonsendring i integrasjonspunktet Altinn køyrer. Har gitt beskjed til Stephanie, gir du beskjed til andre som eventuelt har behov for å vite dette?
