### ISSUE TITLE
Make økonomisk-informasjon app for BRG

### ISSUE THREAD

**Issue by tba76** [Altinn/altinn-platform#21]
## Description
TBD

## Acceptance criteria
> Describe criteria here (i.e. What is allowed/not allowed (negative tesing), validations, error messages and warnings etc.)

## Specification tasks
- [x] Understand behaviour/needs of app
- [x] Development tasks are defined

## Development tasks
- [x] Create datamodel 
- [x] Update app in repo and create pages
- [x] Integrate with DAN (DAN-client, Maskinporten)
- [x] Integrate Samtykke

**Comment by SandGrainOne** [comment]
Remaining work transfered to new issue.
