### ISSUE TITLE
Analysere overgang til OpenTelemetry for innsamling av data (trace, metrikker) til application insights

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#218]
Overført fra https://dev.azure.com/digdir/Altinn/_workitems/edit/56416

For enklere å kunne sammenstille trace og metrikker fra traefik, linkerd og våre egenutviklede applikasjoner ønsker vi å kunne benytte https://opentelemetry.io 

Ved å benytte en standard for innsamling av trace og metrikker vil vi kunne analysere hele altinn3 løsningen under ett. Ved å se hele løsningen i monitorerings løsningen vil vi enklere kunne identifisere kilden til treghet eller feil uavhengig av om dette er i 3. parts produkter som traefik og linkerd eller i våre egne eller tjenesteiers applikasjoner.

OpenTelemetry er på dagens tidspunkt ikke regnet som produksjonsklart av alle, men opensource-communities og microsoft ser ut til å legge mye arbeid i å støtte denne standarden.

Analyse av behov finnes her: https://dev.azure.com/digdir/Altinn/_workitems/edit/54488

**Comment by SandGrainOne** [comment]
1. Ny sjekk av modenhet. Er det noe vi nå trygt kan ta i bruk i produksjon?
2. Hva slags verktøy er det tenkt brukt i resten av organisasjonen?

**Comment by bengtfredh** [comment]
Conclusion at this time is that it is not ready to use in full scale ref:
https://github.com/Altinn/altinn-platform/issues/261#issuecomment-1275780459
