### ISSUE TITLE
Document a procedure for safely introducing a demanding database change

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-platform#221]
### Description

We need to identify and document a recommended procedure for database changes that could cause serious performance issues during the process. 

A typical example would be to introduce an index on a table already heavily populated and with a lot of trafic.

### In scope

- Look into recommended procedures for changes that could lead to performance issues.
- Document a recommended procedure the teams can use should the need arrise.

**Comment by acn-sbuad** [comment]
For events we have introduced a registration queue, decoupling the database for the initial registration of an event allowing us to stop processes that interact with the database without affecting the availability of critical endpoints. Closing issue for now. Should we re-opened if we have specific cases for other database types / platform components
