### ISSUE TITLE
Create a github workflow that can put extra review focus on database changes

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-platform#222]
### Description

Database changes can sometimes cause issues. The github wirkflow should detect changes in the Migration folder and ensure that the changes require more than one reviewer. 

### Tasks

- [x] Set up workflow
- [x] QA
- [x] Test

### Acceptance Criterias

- [x] There exists a workflow that labels relevant PRs

**Comment by acn-sbuad** [comment]
![image.png](https://images.zenhubusercontent.com/5c8f655333fd990b927f5ea1/3dac3699-8693-4bee-a74d-e0232f2273f6) 
label successfully added to PR
