### ISSUE TITLE
Utbedre titler under All issues

### ISSUE THREAD

**Issue by annerisbakk** [Altinn/altinn-platform#229]
https://github.com/orgs/Altinn/projects/20/views/1
Må komme bedre frem hvilke saker som skal groomes og hvilke som skal refines. Prøve ut om det er mer effektivt å bli enige om hva som skal refines av hvem - sette to og to sammen, og i plenum presentere hva man har blitt enige om.

**Comment by acn-sbuad** [comment]
Team is happy with current state of titles. Closing issue
