### ISSUE TITLE
Skru på WAF funksjonalitet i application gateway

### ISSUE THREAD

**Issue by annerisbakk** [Altinn/altinn-platform#233]
TFS43747:WAF funksjonalitet er ikke skrudd på for plattform-agw. Det må kjøres både funksjonelle og ytelsestester etter WAF er skrudd på.

Kommentar i saken: 
Bang-Olsen, Henrik
[commented 12. okt. 2020](https://dev.azure.com/digdir/Altinn/_boards/board/t/Team%20Commodore/Stories#9710)
 

Det har blitt kjørt k6 tester på yt01-agw01 før WAF ble slått på, resultatet fra disse testene blir sammenlignet med tester der WAF står på i forskjellige moduser, og med forskjellige rulesets.

WAF ble slått på i yt01-agw01 med detection mode og OWASP_3.0 ruleset. K6 tester har blitt kjørt og oppnådde et resultat som ikke påvirker ytelsen og resultatet.

WAF ble slått på i yt01-agw01 med detection mode og OWASP_3.1 ruleset. K6 tester har blitt kjørt og oppnådde et resultat som ikke påvirker ytelsen og resultatet.

WAF ble slått på i yt01-agw01 med prevention mode og OWASP_3.1 ruleset. K6 tester har blitt kjørt og ble umiddelbart blokkert av prevention mode. WAF kunne ikke benytte seg av hvitelisting uten at AGW ble lagt til WAF Policies.

WAF Policies ble slått på i yt01-agw01 med detection mode og OWASP_3.1 ruleset. K6 tester har blitt kjørt og oppnådde et resultat som ikke påvirker ytelsen og resultatet.

Logging av både detection og prevention mode fungerer som det skal.

AGW ser ut til å auto-skalere som den skal.

Det har vært flere tester med feilmeldinger og dårlig resultat, de fleste av disse er knyttet til andre problemer i miljøet og resten kan skyldes problemer med VPN tunnelen hos Basefarm.

Ønsker å teste videre med prevention mode og hvitelisting men jeg behøver tilgang til å trigge K6 pipelines for å ikke bruke opp tiden til Jeeva og Petter.

**Comment by annerisbakk** [comment]
@jvsimo Synspunkt på denne saken?

**Comment by jvsimo** [comment]
Fra et sikkerhetsmessig ståsted burde WAF aktiveres/innføres for Altinn 3.

**Comment by annerisbakk** [comment]
@aas-tbuar @SandGrainOne @altinnadmin Jeg kobler dere på her ift å vurdere hvordan vi skal/kan innføre WAF i Altinn 3

**Comment by altinnadmin** [comment]
Denne er vel "litt" relevant i denne forbindelse? 🙂 https://github.com/Altinn/altinn-platform/issues/382

**Comment by bengtfredh** [comment]
This is a dead issue because we removed application gateway because of performance issues.

**Comment by altinnadmin** [comment]
> This is a dead issue because we removed application gateway because of performance issues.

@bengtfredh Good. We should create a new issue for considering [v2](https://learn.microsoft.com/en-us/azure/application-gateway/overview-v2) in front of app-clusters and all product infrastructures. This makes it possible to [support IPv6](https://azure.microsoft.com/en-us/updates/public-preview-application-gateway-now-supports-ipv6-frontend/) and enable WAF and autoscaling.
