### ISSUE TITLE
Se på felles antimaleware løsning for sky

### ISSUE THREAD

**Issue by annerisbakk** [Altinn/altinn-platform#235]
Tjenester 3.0 har behov for å ha en antimalware løsning som kan scanne for følgende:
- binære vedlegg som lastes opp i forbindelse med innsendinger
- container images
- kjørende containere
- virusscan på vm

Dette bør ses på helhetlig med hva Altinn 2 har og hvilke krav som andre produkter stiller. 

Hans Oluf Waaler
[commented 23. okt. 2020]
 
- Se om eksisterende løsning kan benyttes - sjekke lisensiering
- Definere kravspesifikasjon

**Comment by SandGrainOne** [comment]
Litt mer historikk:
https://github.com/Altinn/altinn-studio/issues/1888

**Comment by acn-sbuad** [comment]
Closing as duplicate of Altinn/altinn-storage#104
