### ISSUE TITLE
Disable deploy pipeline til gammelt AKS cluster for Platform

### ISSUE THREAD

**Issue by ootneim** [Altinn/altinn-platform#24]
Deploy pipeline kan disables får et platform miljø har fått implementert et blue/green cluster.

Status: 
Har foreløpig bare skrudd av deploy til de opprinnelige AKS klustrene i AT21, AT22, AT23 og AT24. Det vil si at Task(s) fortsatt ligger i release pipelines, men er disabled. Kan etter hvert fjerne task(s) helt.

- [x] Authentication
  - [x] AT21
  - [x] AT22
  - [x] AT23
  - [x] AT24
  - [x] YT01
  - [x] TT02
  - [x] PROD
- [x] Authorization
  - [x] AT21
  - [x] AT22
  - [x] AT23
  - [x] AT24
  - [x] YT01
  - [x] TT02
  - [x] PROD
- [x] Events
  - [x] AT21
  - [x] AT22
  - [x] AT23
  - [x] AT24
  - [x] YT01
  - [x] TT02
  - [x] PROD
- [x] Kuberneteswrapper
  - [x] AT21
  - [x] AT22
  - [x] AT23
  - [x] AT24
  - [x] YT01
  - [x] TT02
  - [x] PROD
- [x] PDF
  - [x] AT21
  - [x] AT22
  - [x] AT23
  - [x] AT24
  - [x] YT01
  - [x] TT02
  - [x] PROD
- [x] Profile
  - [x] AT21
  - [x] AT22
  - [x] AT23
  - [x] AT24
  - [x] YT01
  - [x] TT02
  - [x] PROD
- [x] Receipt
  - [x] AT21
  - [x] AT22
  - [x] AT23
  - [x] AT24
  - [x] YT01
  - [x] TT02
  - [x] PROD
- [x] Register
  - [x] AT21
  - [x] AT22
  - [x] AT23
  - [x] AT24
  - [x] YT01
  - [x] TT02
  - [x] PROD
- [x] Storage
  - [x] AT21
  - [x] AT22
  - [x] AT23
  - [x] AT24
  - [x] YT01
  - [x] TT02
  - [x] PROD

**Comment by bengtfredh** [comment]
This issue should include clean up dormant subnets.

**Comment by SandGrainOne** [comment]
@bengtfredh I want to keep this issue focused on cleaning up in the Azure DevOps release pipelines. 

The only Stage that still have the old disabled "helm upgrade" task is the Production Stage, but it exists in all release pipelines for all Platform applications.
