### ISSUE TITLE
Identify the cause of response code 421 from apps.

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-platform#255]
### Description

This issue is created based on support case RFT27720.

#### 
POST https://skd.apps.altinn.no/skd/mva-melding-innsending-v1/instances
returns 421 Misdirected Request (Feilsendt forespørsel)

Happens in both tt02 and prod.
Started happening in May 2022, which is around the time we made a bigger configuration of Traefik.

#### Unrelated problem in log
Attempts to access the URL
https://skd.apps.altinn.no/skd/mva-melding-innsending-v1/instances//feedback/status
results in a response with status code 421.

The URL is missing 2 path elements, the instance owner party id and the instance guid. The theory as of now is that the invalid URL leads to one or more redirects that ends up in a 421.

**Comment by vgr** [comment]
After the system-supplier activated Server Name Indication (SNI) in their Java library, the 421 error stopped happening. The service request has been closed.
