### ISSUE TITLE
Retrospective w39/40

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-platform#261]
## Diskusjon
Mange gode samtaler også rundt de positive punktene. Disse kan sees direkte i boardet: https://metroretro.io/board/LBCOTZ97KFEX

- Det er flere bekymringer rundt backlog/spesifiserig og flyt fra start til slutt
- Vi mangler ressurser med kompetanse på infrastruktur "Bengt og Øystein"-light
  - Noe kan løses med upskilling av utviklere, men ikke alt
- Mangel på monitorering på infrastrukturen som gjør at vi enklere kan fange opp case som BDO sitt
-
- Behov for utbedring av de automatiserte testene våre. For infrastruktur er det ingen tester p.t.
- PDF lovet før jul
 

## Aksjonspunkter
- [ ] Det settes et felles sprintmål for kommende sprint @annerisbakk @SandGrainOne 
  - Forsalg til formulering: "Øke samkoordinering på utvikling"
- [x] Oppstart på vurdering av modenhet av Open Telemetry @bengtfredh 
- [x] Få en oversikt over hvilken dokumentasjon man har kommet over så langt som er manglende / utdater @vgr 
- [ ] I refinement ha et fokus på at issuene skal være "gode nok" trenger ikke landet løsningen  
  - Herunder dependencies, hva skal løses, størrelse på issuet og definition of done

**Comment by bengtfredh** [comment]
From what I can find from documentation. Azure is not ready to use with Open Telemetry by now. To investigate if we can benefit from Open Telemetry we need to lock for other log/monitor system than application insight. That must be out of scope for this issue.
We can use prometheus as a scraper and get selected monitoring point in to application insight. My recommendation is to further investigate if that is something that give us what we need.

---
Telemetry, the data collected to observe your application, can be broken into three types or "pillars":

- Distributed Tracing
- Metrics
- Logs

Initially the OpenTelemetry community took on Distributed Tracing. Metrics and Logs are still in progress. A complete observability story includes all three pillars, but currently our Azure Monitor OpenTelemetry-based exporter preview offerings for .NET, Python, and JavaScript only include Distributed Tracing.

**Comment by vgr** [comment]
Created #280 and #275 to track documentation improvements.
