### ISSUE TITLE
Improve PostgreSQL getting-started documentation

### ISSUE THREAD

**Issue by vgr** [Altinn/altinn-platform#275]
### Description

Relevant articles: 
- External: https://docs.altinn.studio/community/contributing/handbook/postgres/
- Internal: https://pedia.altinn.cloud/altinn-3/dev/postgres/

The internal documentation should complement the external document with non-public steps, otherwise the open document should be as self-contained as possible.

It is fine to lean on external guides such as:
- https://www.postgresql.org/docs/current/tutorial.html
- https://www.postgresqltutorial.com/

but that should be stated in the beginning as prerequisite if so.

Wishlist:
- Current versions. This can be considered reference material, but should be linked to in documents if so.
- Where in code repos we can find relevant sql functions to test out.
- How are the database set up wrt. connections, pooling, db users, rights, security considerations, etc.

**Comment by SandGrainOne** [comment]
Not prioritised.
