### ISSUE TITLE
Ownership of db resources has changed after migration to flexible server

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-platform#286]
### Description of the bug

After migrating the Events db to flexible server, resources such at tables and function have changed ownership. 

Instead of the owner being set as platform_events_admin it is changed to the db admin user. This restricts what the migration script in what actions it can take. 

![image](https://user-images.githubusercontent.com/47737608/196939110-59c4a950-2973-43fe-ad9f-0afcbcb2934b.png)

We need to document how to handle this. Either automatically (with a SQL script) or manually during the migration. Update #201 as needed.

## Expected behavior 

Ownership for all resources in eventsdb events schema is set to platform_events_admin .

### Steps To Reproduce

1. Log onto PGAdmin
2. Open events schema
3. Open a pre-existing function / table
4. Check owner under properties
5. See error

**Comment by ootneim** [comment]
Updated permission for adminuser with Terraform so adminuser can change owner.  Terraform Tag 1.4.8

Then execute the following in pgAdmin:

ALTER TABLE events.events OWNER to platform_events_admin;
ALTER TABLE events.subscription OWNER to platform_events_admin;
ALTER SEQUENCE events.events_sequenceno_seq OWNER TO platform_events_admin;
ALTER SEQUENCE events.subscription_id_seq OWNER TO platform_events_admin;
ALTER PROCEDURE events.deletesubscription(integer) OWNER TO platform_events_admin;
ALTER PROCEDURE events.insert_event(character varying, character varying, character varying, character varying, text) OWNER TO platform_events_admin;
ALTER PROCEDURE events.setvalidsubscription(integer) OWNER TO platform_events_admin;
ALTER FUNCTION events.get(character varying, character varying, timestamp with time zone, timestamp with time zone, text[], text[]) OWNER TO platform_events_admin;
ALTER FUNCTION events.get(character varying, character varying, timestamp with time zone, timestamp with time zone, text[], text[], integer) OWNER TO platform_events_admin;
ALTER FUNCTION events.getsubscription(integer) OWNER TO platform_events_admin;
ALTER FUNCTION events.getsubscriptionsbyconsumer(character varying) OWNER TO platform_events_admin;
ALTER FUNCTION events.getsubscriptionsbyconsumer(character varying, boolean) OWNER TO platform_events_admin;
ALTER FUNCTION events.getsubscriptionsexcludeorgs(character varying, character varying, character varying) OWNER TO platform_events_admin;
ALTER FUNCTION events.insert_subscription(character varying, character varying, character varying, character varying, character varying, character varying, boolean) OWNER TO platform_events_admin;
ALTER FUNCTION events.insertevent(character varying, character varying, character varying, character varying, text) OWNER TO platform_events_admin;
ALTER TABLE public.__yuniql_schema_version OWNER to platform_events_admin;
ALTER TABLE public.__yuniql_schema_version_v1_0 OWNER to platform_events_admin;
ALTER SEQUENCE public.__yuniql_schema_version_sequence_id_seq OWNER TO platform_events_admin;

**Comment by ootneim** [comment]
Dokumentasjon;
https://pedia.altinn.cloud/altinn-3/ops/maintenance/postgresql/change-owner/
