### ISSUE TITLE
Add renovate to terraform iac repos

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#290]
### Description

Repo to add renovate:
- terraform-modules
- tjenesteeier-template

Initially attempt to set up without a lot of restrictions. See what renovate detects and suggests. Adjust accoringly. 

### Tasks

- [ ] Investigate how to run Renovate on a private Azure DevOps repository.
- [ ] Activate Renovate

## Acceptance criteria

- [ ] Renovate is creating pull requests

**Comment by annerisbakk** [comment]
@bengtfredh denne må vel vurderes på nytt når man har tatt beslutning ift flytting til GitHub

**Comment by bengtfredh** [comment]
Not applicable
