### ISSUE TITLE
Set up and verify app cluster for NKOM - NASJONAL KOMMUNIKASJONSMYNDIGHET  (Test)

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#296]
Description
Set up app cluster for NKOM Test

Infrastructure tasks [Documentation](https://pedia.altinn.cloud/altinn-3/infrastructure/environments/create-clusters/app-cluster/)
- [x] Prepare subscription for NKOM test and production  @Herskis 
    - Rename reserved subscriptions and grant "Contributor" and "User Access Administrator" permissions to "Altinn Apps Terraform".
- [x] Create AD-groups for NKOM  @Herskis 
- [x] Prepare pipeline for NKOM test
- [x] Run pipeline for NKOM test
- [x] Create and add access token certificate
- [x] Add dns record for NKOM cluster  @Herskis.  

 
Acceptance criteria
- [x] An application is successfully instantiated and submitted.
- [x] Instance is successfully cleaned up: guid bae6e70d-e6ee-4d0a-ac98-180610ee0f92

Development tasks
- [x] Create org in Altinn Studio
- [x] Give NKOM rights to deploy to Test on cdn
- [x] Create and deploy app to NKOM for NKOM 
- [x] Create slack-channel for NKOM
- [x] Notfify that cluster is ready in slack
- [x] Create scopes in Maskinporten @SandGrainOne 
- [x] Clean up testdata.
  - [x] Complete confirm+ hard delete instance
  - [x] Delete deployment + resources from cluster
  - [x] Delete repository from gitea

**Comment by Herskis** [comment]
Subs, tilganger og grupper er opprettet

**Comment by tba76** [comment]
Cleanup ready for verification 17.11.2022
