### ISSUE TITLE
Apps blob storage herding

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#31]
Se https://docs.microsoft.com/en-us/azure/storage/common/security-baseline for mer informasjon.

Det er spesielt trusselen for at noen kan laste ned fra andre lokasjoner som må mitigeres. Det er kun tillatte lokasjoner og vnet som skal kunne koble til på de forskjellige storage accountene. En må kartlegge hvilke lokasjoner som skal ha tilgang. 

Det er tre typer storage accounts vi har i Altinn 3.0. 
- En felles storage konto der noen policyer blir lagret. Denne aksesseres via platform komponenten. Mulig den aksesseres via andre komponenter også.
- Hver tjenesteeier har sin storage konto der innsendingsdata lagres. Denne aksesseres via platform komponenten. Kan potensielt aksesseres via cleanup funksjonalitet. 
- Backup storage account hvor endringer av metadata fra cosmos db lagres. Aksesseres via en azure function app. Kan også aksesseres via en CLI applikasjon for restore. (Bør kjøres via ai-dev). 

Videreføring av: https://dev.azure.com/digdir/Altinn/_workitems/edit/45108

Tasks:
- [x] Avklare herding tjenesteeier storage account
- [ ] Tidsplan utrulling
- [ ]  Dokumentasjon

**Comment by OddArneSaetervik** [comment]
Ser at saken var satt til medium, men tror at denne sikkerhetsmessige hygiene saken har ligget så lenge at den fortjener å bli ferdigstilt. Jeg satte den derfor til høy nå, for å få dette ferdigstilt.
