### ISSUE TITLE
Adjust startup/readyness/liveness times for eFormidling

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-platform#316]
### Description

Based on #303

**Comment by ootneim** [comment]
Kjører med følgende setting som ser ut til å fungerer ganske bra for AKS 1.24

livenessProbe:
            httpGet:
              path: /manage/health
              port: http
            initialDelaySeconds: 60
            failureThreshold: 3
            periodSeconds: 3
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /manage/health
              port: http
            initialDelaySeconds: 30
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 1
