### ISSUE TITLE
Apps Key Vault herding

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#32]
// Videreføring av: https://dev.azure.com/digdir/Altinn/_workitems/edit/55227

Det bør lages , eller følges regler fra MS eller liknende for hvordan Key Vault herdes. Dette bør være universelle, og brukes for alle key vaults i løsningen. Best practices for using Azure Key Vault | Microsoft Docs

Tasks:
- [ ] Avklare herding av tjenesteeier storage (keyvault)
- [ ] Avklare herding av tjensteeier app key vault
- [ ] Dokumentasjon
- [ ] Utrullingsplan

**Comment by OddArneSaetervik** [comment]
Ser at saken var satt til medium, men tror at denne sikkerhetsmessige hygiene saken har ligget så lenge at den fortjener å bli ferdigstilt. Jeg satte den derfor til høy nå, for å få dette ferdigstilt.

**Comment by bengtfredh** [comment]
Tested if network ip/cidr and vnet added in portal got removed by Terraform. Confirmed it do remove rules added in portal.
