### ISSUE TITLE
Add workflow to register new issues in AOS in All Issues project

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-platform#327]
### Description

https://github.com/Altinn/altinn-application-owner-system

This repository isn't tracked well by team platform. Should be included in all issues project.
Workflow will need to have a check that the repository is within the Altinn-org before running the task

### Tasks

- [ ] Set up workflow
- [ ] QA
- [ ] Test

### Acceptance Criterias
- [ ] new issues in repo are automatically registered in all issues project

**Comment by SandGrainOne** [comment]
Completed at some point in the past
