### ISSUE TITLE
Remove servicedata container in platform storage account

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-platform#329]
## Description
In our platform storage accounts we have a container named servicedata that is not being used. 

Not sure if container is generated by terraform or something else. but is should be removed from existing storage accounts and creation should be excluded from provisioning scripts

## Development tasks
- [x] Identify where the container is created 
- [x] Remove container from existing storage accounts
- [ ] Remove object replication for servicedata

## Test
- [ ] Regression test of Storage

**Comment by ootneim** [comment]
Servicedata container is located in the altinn(env)storage01 storage account

**Comment by ootneim** [comment]
Changes part of tag 1.7.25
deploy to AT and YT first
