### ISSUE TITLE
Add separate subdomains for the Platform components?

### ISSUE THREAD

**Issue by altinnadmin** [Altinn/altinn-platform#330]
## Description
Currently all our Platform microservices lives in https://platform.altinn.no/

This means that it will be difficult to host our microservices in different infrastructures without affecting external systems, f.ex. some in AWS, some in Azure and some on-prem.

To solve this we could introduce separate subdomains for each Platform component, for example:

https://storage.platform.altinn.no
https://profile.platform.altinn.no
etc.

This will be like our app clusters:
https://digdir.apps.altinn.no
https://ssb.apps.altinn.no
etc.

## In scope
> What's in scope of this analysis?

## Out of scope
> What's **out** of scope for this analysis?

## Constraints
If we should do this it should be done early.
When too many orgs star using Altinn 3 this will be very hard to change.

## Conclusion
> Short summary of the proposed solution.

## Tasks
- [ ] Is this issue labeled with a correct area label?
- [ ] QA has been done

**Comment by annerisbakk** [comment]
@SandGrainOne Bør det opprettes et nytt issus for det som evt gjenstår, og lukke denne?

**Comment by SandGrainOne** [comment]
Maybe @altinnadmin can pitch in whether anything has changed or if this still stands.

**Comment by altinnadmin** [comment]
I guess our current push towards moving to independent infrastructures for each product indirectly solves my original concern, since those products then can be hosted anywhere on any domain.

And the decision to use a common APIM across products and move towards a "unified" api.altinn.no domain for external APIs, also makes this issue less relevant as it stands.

So perhaps this just should be closed. Agree @SandGrainOne ?

**Comment by SandGrainOne** [comment]
Enig. Lukkes.
