### ISSUE TITLE
As an app owner I need to be able to set up custom alerts and notifications for my applications

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-platform#332]
## Description
Currently, the T3.0 team monitors all applications, but some appowners would like to set up custom alerts and get notified if an alert is triggered. 

It should be possible to set up custom alerts and set up notification. 

## Specification tasks

- [ ] Development tasks are defined

## Definition of done

- [ ] Documentation is updated (if relevant)
  - [ ] Technical documentation (docs.altinn.studio)
  - [ ] User documentation (altinn.github.io/docs)
- [ ] QA
- [ ] Manual test is complete (if relevant)
- [ ] Automated test is implemented (if relevant)
- [ ] All tasks in this userstory are closed (i.e. remaining tasks are moved to other user stories or marked obsolete)

**Comment by bengtfredh** [comment]
Duplicate
- #322

**Comment by annerisbakk** [comment]
Lukkes som duplikat
