### ISSUE TITLE
Update build- and deploypipelines to fail on standard error

### ISSUE THREAD

**Issue by tba76** [Altinn/altinn-platform#345]
## Description
Some pipelines does not fail when one or more steps fail.

Solution for Loadbalancer, Studio:
Helm upgrade step failed but no error.
Classic pipeline, checked the "Fail on standard error" checkbox. 
Pipeline will fail for warnings, so maybee some commands in inline script must be changed.
Ex. az aks get-credentials: add "--only-show-errors" 

## Acceptance criteria
 - All pipelines is updated to fail on standard error (if possible)

## Specification tasks

- [ ] Development tasks are defined

## Development tasks
- [ ] Identify pipelines affected
- [ ] Update affected pipelines

## Test
> Add test cases here as checkboxes that are being tested as part of the changes.

## Definition of done
Verify that this issue meets [DoD](https://digdir-digitalisering.atlassian.net/wiki/spaces/T3KP/pages/5049246/Definition+of+Done) (Only for project members) before closing.

- [ ] Documentation is updated (if relevant)
  - [ ] Technical documentation (docs.altinn.studio)
  - [ ] User documentation (altinn.github.io/docs)
- [ ] QA
- [ ] Manual test is complete (if relevant)
- [ ] Automated test is implemented (if relevant)
- [ ] All tasks in this userstory are closed (i.e. remaining tasks are moved to other user stories or marked obsolete)

**Comment by aas-tbuar** [comment]
@tba76 Skal denne lukkes?

**Comment by annerisbakk** [comment]
Lukkes etter tilb.melding fra Thomas
