### ISSUE TITLE
Create a new Storage Account for Authorization

### ISSUE THREAD

**Issue by ootneim** [Altinn/altinn-platform#348]
Requirements:

- Snapshots enabled

This will be used for ResourceRegistry XACML Policies

Task
- [x] Create storage accound
- [x] Add credentions to KeyVault 

```json
  "AzureStorageConfiguration": {
    "ResourceRegistryAccountName": "xxxx",
    "ResourceRegistryAccountKey": "xxxx",
    "ResourceRegistryBlobEndpoint": "xxxx",
  },
```

**Comment by ootneim** [comment]
@TheTechArch 
Hva slags snapshot policy ønskes?
Eller er det versonering dere ser etter?

**Comment by TheTechArch** [comment]
Jeg så desverre ikke kommentaren på dette. Vi trenger tilsvarende blob storage som vi har på delegation
