### ISSUE TITLE
Analyze options for generating PlatformAccessToken for testing

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-platform#353]
### Description

Currently, we are dependent on an Altinn App to generate a platform accessToken. 
Being able to generate the token or bypass the token requirement for automated tests will allow us to test our platform components in a more isolated way without exessive dependencies.

**Comment by SandGrainOne** [comment]
Altinn test tools with the token generator can generate Altinn platform access tokens. It's not able to generate App access tokens. This means it can not generate a token that appear to be from an App with application owner as issuer. I like to believe this is good enough.
