### ISSUE TITLE
Implement logic in messagebox for copying archived instances

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-platform#355]
## Description

Copying an archived instance should also be supported for Altinn 3 apps. The view should match the view for ReporteeElements in Altinn 2.

The portal button/link should send the user to the app which performs the instantiation based on existing instance. The App already have a POST endpoint that allows for creating a new instance based on an existing instance. It's needs a GET endpoint that can perform the same logic and then do a redirect to the new endpoint.

Endpoint suggestion:
/{org}/{app}/instances/{instanceId}/copy

## Development tasks
- [x] Extend the messagebox instance model with a field for identifying if copy is enabled
    - The MessageBoxInstance model exposed by Storage already have a property AllowNewCopy
- [x] Implement a GET endpoint in InstanceController in App that can be the entry point for the Copy feature.
    - The logic performs the instantiation of the new instance and redirects the user to the new instance.
    - Any error redirects the user to an error page?
- [x] Add new property to mapping in InstanceHelper in Storage
    - The value can be set based on the CopyInstanceSettings on the Application model. 
    - Use the Enable property to create an authorization request to ensure that the user have the necessary rights to instantiate. 
    - The immediate logic doesn't have access to Application. This must be added. Preferably with some sort of caching.
    - The property AllowNewCopy should be set only when requesting a single instance
- [x] Fix relevant .cshtml files in SBL
    - [x] ArchiveReportingElementInfo.cshtml
- [x] Fix ArchiveReportingElementInfo.cshtml to use correct endpoint URL.

## Testing

An app with the copy archived instance feature already enabled has been deployed to TT02:
https://ttd.apps.tt02.altinn.no/ttd/copy-instance-tester/

The app can be used by any reportee. One possible confusion is that the app has two form filling steps so you need to submit two forms which are identical. The intent was to test the ExcludeDataType feature, but that's not supported as of now. ExcludedDataFields can be tested, but the deployed app has no excluded fields. 

To test "make new instance based on existing instance" create a direct URL based on this template:
https://ttd.apps.tt02.altinn.no/ttd/copy-instance-tester/legacy/instances/{partyid}/{instanceGuid}/copy

## Acceptance criteria
- [x] An app with copy disabled will return 400 with appropriate message
- [x] An instance that hasn't been archived will result in 400 with appropriate message
- [ ] An archived instance from an app with copy enabled will have copy enabled (messagebox)
    - [x] Also requires that the user is allowed to read and instantiate. 
    - [ ] As of writing this the link from the portal is wrong. Will be hotfixed. You can still click the link. The browser will get a 404, but from here you can easily manipulate the url.
- [x] The message box panel displays a copy button for instances with copy enabled.
- [ ] Clicking the button generates a new instance based on the archived instance and the user is redirected to the new instance.
- [x] Only datatypes with a ClassRef and for the first Task in the process is copied
    - This makes it impossible to test ExcludedDataType

## Definition of done
Verify that this issue meets [DoD](https://digdir-digitalisering.atlassian.net/wiki/spaces/T3KP/pages/5049246/Definition+of+Done) (Only for project members) before closing.

- [ ] Documentation is updated (if relevant)
    - [ ] Technical documentation (docs.altinn.studio)
    - [ ] User documentation (altinn.github.io/docs)
- [ ] QA
- [ ] Manual test is complete (if relevant)
- [ ] Automated test is implemented (if relevant)
- [ ] All tasks in this userstory are closed (i.e. remaining tasks are moved to other user stories or marked obsolete)

**Comment by acn-sbuad** [comment]
Comments from first round of testing: 

- 404 result code for apps with an old template version when attempting to copy instance directly towards url. Expected I guess. 
- an issue should exists for completing/verifying the functionality related to ExcludedDataType. 
- no acceptance criteria related to documentation. Is this on your To-do list @SandGrainOne  ? Or on the apps teams list of things to do? 

Waiting to verify logic related to button and link until after SBL hot fix.

**Comment by acn-sbuad** [comment]
Attempting to copy an instance based of a non-existing instanceId result in a 500 error. Should we have any error handling here to control the result code in some way ?

**Comment by SandGrainOne** [comment]
> Attempting to copy an instance based of a non-existing instanceId result in a 500 error. Should we have any error handling here to control the result code in some way ?

Managed to find out what it is that is going wrong. The InstanceClient in Core creates a PlatformHttpException if the response from Storage is non successful. I've made a PR to handle it slightly better:

https://github.com/Altinn/app-lib-dotnet/pull/236
