### ISSUE TITLE
Enable Application Insights to get data from AKS

### ISSUE THREAD

**Issue by knuthalvor** [Altinn/altinn-platform#361]
## Description
Related to Issue Altinn/altinn-studio#3723 and Altinn/altinn-studio#3103 . The existing package published for  ApplicationInsights.Kubernetes is not necessarily ideal in relation to security issues.
The package has been forked, https://github.com/Altinn/ApplicationInsights-Kubernetes, and needs to be updated so that it only collects information from the Pod. We will then either then open an issue and push this back to the original package, or create our own package for this to be included in our applications (apps and platform).

## Specification tasks

- [ ] Development tasks are defined
- [ ] Test design / decide test need

## Development tasks
- [ ] Update forked repository

## Definition of done
Verify that this issue meets [DoD](https://confluence.brreg.no/display/T3KP/Definition+of+Done#DefinitionofDone-DoD%E2%80%93utvikling) (Only for project members) before closing.

- [ ] Documentation is updated (if relevant)
  - [ ] Technical documentation (docs.altinn.studio)
  - [ ] User documentation (altinn.github.io/docs)
- [ ] QA
- [ ] Manual test is complete (if relevant)
- [ ] Automated test is implemented (if relevant)
- [ ] All tasks in this userstory are closed (i.e. remaining tasks are moved to other user stories or marked obsolete)

**Comment by bengtfredh** [comment]
N/A
