### ISSUE TITLE
Upgrade Platform AKS cluster to 1.25.6

### ISSUE THREAD

**Issue by ootneim** [Altinn/altinn-platform#376]
Update AKS cluster in Platform and Eformidling to 1.25.6 (from 1.24.6)

- [x] Platform AT21
- [x] Platform AT22
- [x] Platform AT23
- [x] Platform AT24
- [x] Platform YT01
- [x] Platform TT02
- [x] Platform Prod
- [x] Eformidling TT02
- [x] Eformidling Prod

**Comment by bengtfredh** [comment]
@simon-ellefsen Is there a good reason for not going to 1.25.x?
I do not think there is any deprecations that effects us.
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-25
