### ISSUE TITLE
Upgrade apps kubernetes cluster v1.22.x

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#38]
We are now on v1.21.7. We can upgrade to v1.21.9, but it is better to jump to 1.22.6.
1.20 will be removed on April 7th, v1.21.7 will probably be removed in May.

**Comment by tjololo** [comment]
Apps clusters can be updated even if designer and repos uses deprecated apis since they run in a separate cluster.
https://github.com/Altinn/altinn-studio/issues/7103 should not block this issue. #62 is a possible blocker on the other hand

**Comment by bengtfredh** [comment]
If block is not released upgrade to 1.21.9
