### ISSUE TITLE
Migrate deprecated k8s manifests that will be removed in v1.22

### ISSUE THREAD

**Issue by tjololo** [Altinn/altinn-platform#4]
## Description
Studio is still using some deprecated api versions of the ingress manifests that will be removed in kubernetes 1.22
[Kubernetes migration guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22)

## Considerations
There should be no changes in user experience after the migration.

### Ops requirements
Rollback to version pre migration will no be possible after kubernetes is upgraded to kubernetes > 1.22

## Development tasks
- [x] Upgrade manifests in traefik chart or move to official helm-chart by traefik
- [x] Upgrade linkerd to > 2.10.0
- [x] Upgrade kured to > 2.10.0 [see kubernetes--os-compatibility](https://github.com/weaveworks/kured#kubernetes--os-compatibility) and [kured helm-chart versions](https://artifacthub.io/packages/helm/kured/kured) to find compatible version

**Comment by bengtfredh** [comment]
Issue is resolved
