### ISSUE TITLE
Instansen til Altinn3-appen ser ut til å havne i en "feilmodus" som får eksterne kall ut til å feile

### ISSUE THREAD

**Issue by KristofferMagelssen** [Altinn/altinn-platform#404]
### Description of the bug

Konsekvens:
Når det først skjer kan det få alt av innsendinger til å stoppe opp, og kan ta timer før noen får det med seg. Noe som kan være kritisk før forfall.

Skjedde på skd/mva-melding-innsending-v1 i Produksjon.
Gjelder når egen opprettet HttpKlient prøver å kalle ut fra altinn-appen til DigDir's maskinporten tjeneste. 

Instansen/pod`en(e) til Altinn3-appen ser ut til å havne i en "feilmodus" som får alle kall til maskinporten til å feile med følgende melding:

`The SSL connection could not be established, see inner exception. Received an unexpected EOF or 0 bytes from the transport stream. `
Ble først rapportert 16. Desember 2022. Altinn restartet pod`en som var påvirket.

4. Januar 2023 skjedde det igjen.

Fra Altinn på slack:
> Vi mener at vi har klart å gjennskape problemet i sammenheng med noe ytelsestesting. Det jobbes videre med å forsøke identifisere hvor problemet oppstår og hvorfor. Litt for tidlig å si når vi har en løsning.
> 
> Vi har klart å spore EOF meldingen tilbake til linkerd og har funnet frem til en mulig løsning.
> Den aktuelle endringen er dokumentert i følgende pull request mot vår test app. 
> 
> Endringen har gitt gode resultater med tanke på SSL problemene.
> https://altinn.studio/repos/ttd/skattemelding-kopi/pulls/1/commits

25. Januar 2023 skjedde det igjen, etter å ha lagt inn den mulige løsningen som Altinn foreslo.
- Løste med å deploye ny versjon hvor timeout til linkerd var økt fra 25s til 30s. 

6. Februar 2023:
Ny type feilmelding, men ved samme steg i innsendingsløpet og ellers like oppførsel som feilen beskrevet over.

`Parameters: Connection String: RunAs=App;AppId=78e56ec8-89b0-4cf5-b124-5cf84ea80488;TenantId=cd0026d8-283b-4a55-9bfa-d0ef4a8ba21c;AppKey=<<Redacted>>, Resource: https://vault.azure.net, Authority: https://login.windows.net/cd0026d8-283b-4a55-9bfa-d0ef4a8ba21c. Exception Message: Access token could not be acquired. The SSL connection could not be established, see inner exception.  `

### Steps To Reproduce

Vi har ikke klart å re-produsere den selv, men utifra melding på slack ser det ut som dere har allerede klart det.

> Vi mener at vi har klart å gjennskape problemet i sammenheng med noe ytelsestesting. Det jobbes videre med å forsøke identifisere hvor problemet oppstår og hvorfor. Litt for tidlig å si når vi har en løsning.
> 
> Vi har klart å spore EOF meldingen tilbake til linkerd og har funnet frem til en mulig løsning.
> Den aktuelle endringen er dokumentert i følgende pull request mot vår test app. 
> 
> Endringen har gitt gode resultater med tanke på SSL problemene.
> https://altinn.studio/repos/ttd/skattemelding-kopi/pulls/1/commits

### Additional Information

label: org/skd

**Comment by SandGrainOne** [comment]
@KristofferMagelssen 
Det er nå blitt laget en ny versjon av charts for apps: 2.8.0 hvor det er lagt inn en [endring](https://github.com/Altinn/altinn-studio-charts/commit/0123e9862d87cc147ceee9d1c9b248dc8be8ebf6) vi mener gir en god effekt. Er det noe dere kunne testet ut i deres app?

Det er fortsatt vanskelig å fremprovosere feilen. Dette betyr at vi fortsatt ikke har helt kontroll på årsakssammenhengen. 

Jeg har sett litt i Application Insights for SKD for de siste 30 dager. I produksjon har det ikke vært ett eneste innslag, men i TT02 er det noen sporadiske hendelser. For eksempel er det registrert 5 hendelser 9. mars.

**Comment by KristofferMagelssen** [comment]
> @KristofferMagelssen Det er nå blitt laget en ny versjon av charts for apps: 2.8.0 hvor det er lagt inn en [endring](https://github.com/Altinn/altinn-studio-charts/commit/0123e9862d87cc147ceee9d1c9b248dc8be8ebf6) vi mener gir en god effekt. Er det noe dere kunne testet ut i deres app?
> 
> Det er fortsatt vanskelig å fremprovosere feilen. Dette betyr at vi fortsatt ikke har helt kontroll på årsakssammenhengen.
> 
> Jeg har sett litt i Application Insights for SKD for de siste 30 dager. I produksjon har det ikke vært ett eneste innslag, men i TT02 er det noen sporadiske hendelser. For eksempel er det registrert 5 hendelser 9. mars.

@SandGrainOne Har laget en pull request for å få 2.8.0 av charts i skd/mva-melding-innsending-v1

**Comment by KristofferMagelssen** [comment]
Har lagt ut ny versjon med chart 2.8.0 i tt02 og prod for skd/mva-melding-innsending-v1 nå

**Comment by annerisbakk** [comment]
@SandGrainOne @KristofferMagelssen Hva er status på denne saken nå?

**Comment by SandGrainOne** [comment]
Endringene i helm chart versjon 2.8.0 har hatt god effekt. Vi anser nå denne saken som løst.
