### ISSUE TITLE
Bump terraform and providers apps cluster March 2023

### ISSUE THREAD

**Issue by Herskis** [Altinn/altinn-platform#427]
### Description

Bump terraform and providers.  [Documentation](https://pedia.altinn.cloud/altinn-3/ops/patching/terraform/apps/)

terraform_old="1.3.8"
terraform_new="1.4.0"
azurerm_old="3.43.0"
azurerm_new="3.47.0"
azuread_old="2.33.0"
azuread_new="2.36.0"
tls_new="4.0.4" - Ingen endring
null_new="3.2.1" - Ingen endring
time_new="0.9.1" - Ingen endring
helm_new="2.9.0" - Ingen endring
kubernetes_old="2.18.0"
kubernetes_new="2.18.1"
kubectl_new="1.14.0" - Ingen endring

### Additional Information

Can be used as training.

Look at pedia doc. Check `bump-provider-versions.sh` , and try to find out what new versions of terraform and providers we will update to - use a search engine i.e. https://duckduckgo.com/?q=terraform+provider+azurerm  
Check if there are changes that can affect us.

### Tasks

- [ ] AT_ring1
- [ ] AT_ring2
- [ ] TT_ring1
- [ ] TT_ring2
- [ ] Registry_ring1
- [ ] Registry_ring2
- [ ] Prod_ring1
- [ ] Prod_ring2

### Acceptance Criterias

- iac code run without warning
- "Bruksmønster" run without error

**Comment by bengtfredh** [comment]
As part of improvement of process to bump terraform and provider versions, all versions is bumped to latest.

**Comment by bengtfredh** [comment]
Doc is updated with how to patch with improved procedure:
https://pedia.altinn.cloud/altinn-3/ops/patching/terraform/apps/
