### ISSUE TITLE
Implement backup of Storage Account Tables

### ISSUE THREAD

**Issue by ootneim** [Altinn/altinn-platform#434]
- [x] Analyze how to take backup of tables
- [x] Implement solution
- [x] Test backup 
- [x] Document solution in Altinnpedia

Azure Table Storage doesn't have any backup capability. Need to look into "manual" copy using PowerShell or AzureCli

**Comment by simon-ellefsen** [comment]
Deployed to all environments with Platform tag 1.6.6.1
