### ISSUE TITLE
Byggmaskin herding 

### ISSUE THREAD

**Issue by annerisbakk** [Altinn/altinn-platform#45]
https://dev.azure.com/digdir/Altinn/_workitems/edit/35948
Bygge- og deploymaskinene blir provisjonert med terraform består av Ubuntu og Virtual Machine Scalesets. 

Standardoppsettet:
All innkommende trafikk er blokkert
Basert på Ubuntu
Pakker/Programvare blir eksplisitt installert
Pakkene/Programvaren blir ikke automatisk oppdatert, men agentene er basert på ubuntu 20.10 (latest) når de provisjoneres
Maskinene er ikke CIS-herdet

- [ ] Oppgraderings-/patching regime

- [ ] Tilgangskontroll

- [ ] Kobling til loggsystem

- [ ] CIS herding av maskinene

- [x] Brannmur/nsg

- [x] Backup hvis nødvendig, evt dokumentert

**Comment by annerisbakk** [comment]
@SandGrainOne Fra kommentarfeltet på opprinnelig sak i Azure https://dev.azure.com/digdir/Altinn/_workitems/edit/35948 har sikkerhet vært involvert. Hvem kan vurdere denne saken?
Raymond Andre Hagen
[commented 1. okt. 2020](https://dev.azure.com/digdir/Altinn/_boards/board/t/Team%20Infrastruktur/Stories#9815)
 Har oppdatert "Dev-build-01/2/3/4 til Ubuntu  20.04.01 LTS, skal se om det finnes en måte å automatisere oppdateringer på

**Comment by SandGrainOne** [comment]
@annerisbakk Team Core har hatt begrenset eierskap til bygg servere. Mulig Espen har noe kontroll, men tror også Vemund har vært involvert. Kanskje høre med de om vi bør gjøre ytterligere tiltak her.

**Comment by annerisbakk** [comment]
@Herskis @tjololo Synspunkt på denne?
