### ISSUE TITLE
chore: Upgrade apps AKS to v1.26.x (Breaking Change)

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#452]
#### Deprecated API
HorizontalPodAutoscaler
The autoscaling/v2beta2 API version of HorizontalPodAutoscaler is no longer served as of v1.26.

Migrate manifests and API clients to use the autoscaling/v2 API version, available since v1.23.
All existing persisted objects are accessible via the new API

#### AKS persistent volume
Starting with Kubernetes version 1.21, AKS only uses CSI drivers by default and CSI migration is enabled. While existing in-tree persistent volumes continue to function, starting with version 1.26, AKS will no longer support volumes created using in-tree driver and storage provisioned for files and disk.
https://github.com/Altinn/altinn-platform/issues/374

### Breaking Change
deployment Chart >=2.0.0 and <2.3.0
All apps need to upgrade dependencies  to deployment to version >=2.3.0
We recommend to upgrade to latest available of deployment chart https://github.com/Altinn/altinn-studio-charts/releases

## NB!
Developers are notified to upgrade to supported Charts before end of September 2023. This upgrade ca start in October 2023.

**Comment by bengtfredh** [comment]
blocked by #374

**Comment by annerisbakk** [comment]
@bengtfredh Den som blokkerer er lukket. Kan denne også lukkes?
