### ISSUE TITLE
Scrape prometheus metrics from service owner app

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-platform#453]
## Description
Add a metrics endpoint for prometheus to an app to test collection of data from apps. This is a firsst step issue. The primary objective is to add a little bit of metrics and make them available. Additional metrics can be added over time.

### Start metrics
- Number of started processes
- Number of completed processes
   - Process duration
- Number of failed validations

## Additional information
Library and documentation.
https://learn.microsoft.com/en-us/dotnet/core/diagnostics/metrics-collection
https://github.com/prometheus-net/prometheus-net

**Comment by annerisbakk** [comment]
Lukkes - Apps-teamet har ansvaret.
