### ISSUE TITLE
Update DNS with CNAME for CosmosDB and PostgreSQL

### ISSUE THREAD

**Issue by ootneim** [Altinn/altinn-platform#457]
Add CNAME record for CosmosDB and PostgreSQL servers in DNS.

- For at2x and yt01 use altinn.cloud
- For tt02 and prod use altinn.no

Espen create the records in altinn.no

**altinn.cloud**
at21-cosmosdb.altinn.cloud -> altinn-at21-cosmos-db.documents.azure.com
at21-events-postgre.altinn.cloud -> altinn-events-db-at21-pgflex.postgres.database.azure.com
at21-authorization-postgre.altinn.cloud -> altinn-authorization-db-at21-pgflex.postgres.database.azure.com

at22-cosmosdb.altinn.cloud -> altinn-at22-cosmos-db.documents.azure.com
at22-events-postgre.altinn.cloud -> altinn-events-db-at22-pgflex.postgres.database.azure.com
at22-authorization-postgre.altinn.cloud -> altinn-authorization-db-at22-pgflex.postgres.database.azure.com

at23-cosmosdb.altinn.cloud -> altinn-at23-cosmos-db.documents.azure.com
at23-events-postgre.altinn.cloud -> altinn-events-db-at23-pgflex.postgres.database.azure.com
at23-authorization-postgre.altinn.cloud -> altinn-authorization-db-at23-pgflex.postgres.database.azure.com

at24-cosmosdb.altinn.cloud -> altinn-at24-cosmos-db.documents.azure.com
at24-events-postgre.altinn.cloud -> altinn-events-db-at24-pgflex.postgres.database.azure.com
at24-authorization-postgre.altinn.cloud -> altinn-authorization-db-at24-pgflex.postgres.database.azure.com

yt01-cosmosdb.altinn.cloud -> altinn-yt01-cosmos-db.documents.azure.com
yt01-events-postgre.altinn.cloud -> altinn-events-db-yt01-pgflex.postgres.database.azure.com
yt01-authorization-postgre.altinn.cloud -> altinn-authorization-db-yt01-pgflex.postgres.database.azure.com

**altinn.no**
tt02-cosmosdb.altinn.no -> altinn-tt02-cosmos-db.documents.azure.com
tt02-events-postgre.altinn.no -> altinn-events-db-tt02-pgflex.postgres.database.azure.com
tt02-authorization-postgre.altinn.no -> altinn-authorization-db-tt02-pgflex.postgres.database.azure.com

cosmosdb.altinn.no -> altinn-prod-cosmos-db.documents.azure.com
events-postgre.altinn.no -> altinn-events-db-prod-pgflex.postgres.database.azure.com
authorization-postgre.altinn.no -> altinn-authorization-db-prod-pgflex.postgres.database.azure.com

**Comment by ootneim** [comment]
Endringer er utført for AT21, AT22, AT23, AT24 og YT01

**Comment by ootneim** [comment]
Updated DNS information in AltinnPedia

- https://pedia.altinn.cloud/altinn-3/ops/backup-recovery/platform/cosmosdb/
- https://pedia.altinn.cloud/altinn-3/ops/backup-recovery/platform/postgresql/

**Comment by Herskis** [comment]
@ootneim 
Da er det utført for Prod og TT02 på altinn.no
