### ISSUE TITLE
Configure retention setting on Log Analytics Workspace

### ISSUE THREAD

**Issue by ootneim** [Altinn/altinn-platform#474]
Log Analytics Workspace for production:

- Configure total retention on large tables to 1 year
- Interactive period must be set to 90 days
- Document procedure in AltinnPedia

(Default workspace setting should remain at 1 year).

**Comment by annerisbakk** [comment]
@simon-ellefsen @ootneim Er denne fremdeles aktuell å gjøre? Evt targetdate?

**Comment by Herskis** [comment]
Løses enkelt ved etablering av nye Sentinel for SOC
