### ISSUE TITLE
Change backup of Fileshare to use hourly backup (every 4 hours) new in AzureRM 3.60 provider

### ISSUE THREAD

**Issue by ootneim** [Altinn/altinn-platform#502]
Change terraform scripts to take hourly backups of fileshare instead of daily.
This is new in Terraform Azurerm provider 3.60

azurerm_backup_policy_file_share - support for day-based retention policies and hourly backups (https://github.com/hashicorp/terraform-provider-azurerm/issues/21529)

Takes backup every 4 hours instead of once a day.

**Comment by simon-ellefsen** [comment]
Deployed to all environments with Platform tag 1.6.6.1
