### ISSUE TITLE
Add deploy pipeline for altinn-dashboards-grafana

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#507]
Add pipeline to deploy helm chart altinn-dashboard-grafana.
Can use same config as pdf-generator.

**Comment by acn-sbuad** [comment]
Validated in AT. Automated schedule for tt and prod disabled. Will be disabled once reported ready by @bengtfredh

**Comment by bengtfredh** [comment]
@acn-sbuad tt is ready for deploy
