### ISSUE TITLE
Ytelsestesting for delegation events for platform

### ISSUE THREAD

**Issue by ootneim** [Altinn/altinn-platform#51]
- [ ] Analyser ytelsespåvirkning
- [ ] Ytelsestest

**Comment by tba76** [comment]
Should this task be moved to another repository? @ootneim

**Comment by annerisbakk** [comment]
@ootneim Hva gjør vi med denne?

**Comment by ootneim** [comment]
@annerisbakk ser denne er ganske gammel (ca 2 år) og blir vel en del av generell ytelestesting for platform. Så kan kanskje lukke denne.
