### ISSUE TITLE
Set up and verify app cluster for OED - Olje- og energidepartementet (Test)

### ISSUE THREAD

**Issue by tba76** [Altinn/altinn-platform#519]
## Description
Set up app cluster for OED Test

## Infrastructure tasks [Documentation](https://pedia.altinn.cloud/altinn-3/infrastructure/environments/create-clusters/app-cluster/)
- [x] Prepare subscription for OED test and production  @Herskis 
    - Rename reserved subscriptions and grant "Contributor" and "User Access Administrator" permissions to "Altinn Apps Terraform".
- [x] Create AD-groups for OED @Herskis 
- [x] Prepare pipeline for OED test
- [x] Run pipeline for OED test
- [x] Add dns record for OED cluster  @Herskis.  
- [x] Add synthetic availibilty test https://altinnapps.grafana.net/a/grafana-synthetic-monitoring-app/checks  
          - Job Name: `<org>-<env>`
          - Target: `https://<org>.apps.<env>.altinn.no/kuberneteswrapper/api/v1/deployments`
          - Probe Location: Amsterdam
          -  Frequency - Evry - 30s
          - Validation - Regex Validation - Check fails if response body matches : `kuberneteswrapper` (invert match)
          - Advanced options - labels - `env:<env>`

## Development tasks
- [x] Create org in Altinn Studio
- [x] Give OED rights to deploy to Test on cdn
- [x] Create and deploy app to TT02 for OED
- [x] Create slack-channel for OED
- [ ] Notfify that cluster is ready in slack
- [x] Create scopes in Maskinporten @SandGrainOne 
- [x] Clean up testdata.
  - [x] Complete confirm+ hard delete instance
  - [x] Delete app metadata from cosmos
  - [x] Delete deployment + resources from cluster
  - [x] Delete repository from gitea

 
## Acceptance criteria
- [x] An application is successfully instantiated and submitted.
- [x] Instance is successfully cleaned up: guid 7bda8311-3319-4c36-a41e-d3d29b187ad8

**Comment by Herskis** [comment]
@tba76 Da skal det være klart for verifisering!

**Comment by tba76** [comment]
Cleanup ready for verification 05.07.23
