### ISSUE TITLE
Update tje keyvault to accept connection from new function apps for platform

### ISSUE THREAD

**Issue by ootneim** [Altinn/altinn-platform#542]
Update the tje keyvault firewall to accept connection from the new function apps for platform.

The new function apps have the same name  as the old but ends with "-fa" instead of "-func"

Rollout

- [x] AT
- [x] TT
- [x] PROD

**Comment by bengtfredh** [comment]
Add platform-01 as allowed subnet for each environment.

**Comment by acn-sbuad** [comment]
Verified ok in at22
