### ISSUE TITLE
Add maskinporten JWK secret to platform key vault

### ISSUE THREAD

**Issue by simon-ellefsen** [Altinn/altinn-platform#547]
Task from team autorisasjon:
Create maskinporten JWK secret in the platform key vault for each environment, only prod has a unique value the rest are identical.
The secrets will expire one year after creation. 
We need to create a routine for updating them, as it requires changes on the client side and the platform key vault.

- [x] Secret created in AT21-24 platform key vaults
- [x] Secret created in TT02 platform key vault
- [x] Secret created in YT01 platform key vault
- [x] Secret created in PROD platform key vault
- [x] Expiration date of one year added for secrets
- [x] Routine created for updating JWK secret
- [x] Add slack notification for expiration on the secrets

**Comment by SandGrainOne** [comment]
Wating for production values.
