### ISSUE TITLE
Migrate to Azure Monitor Agent from Log Analytics agent

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#579]
### Description

The Log Analytics agent will be [retired on August 31, 2024](https://azure.microsoft.com/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/). After this date, Microsoft will no longer provide any support for the Log Analytics agent. If you're currently using the Log Analytics agent with Azure Monitor or [other supported features and services](https://learn.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration#migrate-additional-services-and-features), start planning your migration to Azure Monitor Agent by using the information in this article.

### Additional Information

This needs to be done to set up network monitoring in Azure.

**Comment by bengtfredh** [comment]
Hvis dere benytter MMA i dag, så anbefaler jeg at dere lager en plan for migrering. Deler noen tips med dere på dette:

 

Dere kan selv identifisere legacy agenter og følge med på status ved å bruke  [Azure Monitor Migration Helper](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fazure-monitor%2Fagents%2Fazure-monitor-agent-migration-tools%23using-ama-migration-helper&data=05%7C02%7Cbengt.rino.fredh%40digdir.no%7Caf7b75c295194a27487608dc48ee6c33%7C008e560f08af4ceca056b35447503991%7C0%7C0%7C638465436928129798%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=J2lP6VB7pSCmzNPJXYVf%2B3QMg5rKGLJ0s0WJPP4GhAE%3D&reserved=0).
Lær mer om [AMA migrering](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fazure-monitor%2Fagents%2Fazure-monitor-agent-migration&data=05%7C02%7Cbengt.rino.fredh%40digdir.no%7Caf7b75c295194a27487608dc48ee6c33%7C008e560f08af4ceca056b35447503991%7C0%7C0%7C638465436928140361%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=RMn9pdT%2B%2FVpIxeZ2DbwvdxT8AT7hrixU4ZWjeh4yta8%3D&reserved=0)
Her finner dere noen nyttige [verktøy for migreringen](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fazure-monitor%2Fagents%2Fazure-monitor-agent-migration-tools&data=05%7C02%7Cbengt.rino.fredh%40digdir.no%7Caf7b75c295194a27487608dc48ee6c33%7C008e560f08af4ceca056b35447503991%7C0%7C0%7C638465436928149616%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=IGFv4OeSkhCRhXO3oebERQpvPhqMG%2FLIxnT5%2BppQZDI%3D&reserved=0)

**Comment by borgethommesen** [comment]
Identifisert hvor MMA kjøres nå og gjøre forsøk på å migrere til ny løsning (AMA).
Testet å installere AMA på en VM og ha MMA installert for å sjekke migreringsprogresjon.
Testet å installere AMA og avinstallere MMA.
Dette gjort med script samt manuelt.

**Comment by bengtfredh** [comment]
Before Friday 12. March 2024 decide if we want help from MS.

**Comment by borgethommesen** [comment]
Scoping call with Microsoft on 2nd of May. New session on 22nd of May.

Virtual Machine scale sets decided not to migrate due to no monitoring agents currently installed and monitoring handled with other mechanisms.

Virtual machine migration in progress. Found an obstacle that was due to firewall settings. The solution was to run the scripts from an image instead of from local machine.

35% done early 3rd May 2024. Migration in progress for the rest 65%.

**Comment by borgethommesen** [comment]
6 resources (VMs) remain in Subscription Altinn-SBL-Test. These are VMs with functionality that is no longer operational (EDB and SBDB).
Suggest that the VMs be deleted.
at21-edb01
at22-edb01
at23-edb01
at24-edb01
at23-sbdb01
at24-sbdb01
