### ISSUE TITLE
Rollout backup for apps blob storage all environments

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#60]
Terraform code i written and deployed in TTD-AT21.

- [x] Review if backup is right level
- [x] Add new subscriptions for backup-apps
- [x] Add variable backup_enabled for iac

- [x] Rollout backup at
- [x] Rollout backup tt_ring1
- [ ] Rollout backup tt_ring2
- [x] Rollout backup prod_ring1
- [ ] Rollout backup prod_ring2

**Comment by SandGrainOne** [comment]
Rulles i første omgang ut i alle AT miljøer.
