### ISSUE TITLE
Renew ssl certs expiring at 17.01.2024

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#602]
### Description

Following cert will expire:

- [x] 1. Certificate altinn-cert-keyvault: platform-yt01-altinn-cloud is expiring at 17.01.2024!
- [x] 2. Certificate altinn-cert-keyvault: skd-apps-yt01-altinn-cloud is expiring at 17.01.2024!
- [x] 3. Certificate altinn-cert-keyvault: ttd-apps-at2x-altinn-cloud is expiring at 17.01.2024!
- [x] 4. Certificate altinn-cert-keyvault: ttd-apps-yt01-altinn-cloud is expiring at 17.01.2024!

**Comment by bengtfredh** [comment]
Cert is ordered

**Comment by SandGrainOne** [comment]
Managed to run the altinn-audit tool to perform it's check of certificiates and secrets. This was successfull and the alerts on the certificates in this issue has been cleared. Untill next time!
