### ISSUE TITLE
Remove unused CNAME entries for PostgreSQL and CosmosDB in DNS

### ISSUE THREAD

**Issue by ootneim** [Altinn/altinn-platform#615]
Remove unused CNAMES used by PostgreSQL in DNS altinn.cloud and altinn.no
Only the CNAME *-postgres.altinn.cloud (altinn.no) are in use

Remove:
- (env)-events-postgre.altinn.cloud (altinn.no)
- (env)-authorization-postgre.altinn.cloud  (altinn.no)
-  (env)-notifications-postgre.altinn.cloud (altinn.no)
- (env)-storage-postgre.altinn.cloud (altinn.no)

Update TTL to 60 (faster failover)

Remove CNAME for CosmosDB

Environments: Remove in AT2X and YT01 before TT02/PROD
- [x] AT21 (altinn.cloud)
- [x] AT22 (altinn.cloud)
- [x] AT23 (altinn.cloud)
- [x] AT24 (altinn.cloud)
- [x] YT01 (altinn.cloud)
- [x] TT02 (altinn.no)
- [x] PROD (altinn.no)

**Comment by Herskis** [comment]
Da er alle gamle records for postgre og cosmodb fjernet fra altinn.no

**Comment by Herskis** [comment]
![Image](https://github.com/Altinn/altinn-platform/assets/62640845/0f7e524f-3720-40c4-bb64-21cb317e492c)

Begge disse er slettet
