### ISSUE TITLE
Test recovery PostgreSQL from pg_dump for Authorization

### ISSUE THREAD

**Issue by ootneim** [Altinn/altinn-platform#617]
Restore procedure
https://pedia.altinn.cloud/altinn-3/ops/backup-recovery/platform/postgresql/#restore-using-pg_dump-from-a-storage-account

Testing will be done in yt01

- [x] Create Authorization PostgreSQL server.
- [x] Restore Authorization PostgreSQL (Using Backup Vault data)
- [x] Verify

**Comment by annerisbakk** [comment]
Next sprint
