### ISSUE TITLE
Oppdatere rutine for oppsett av miljø med tanke på bestille fast leie av noder.

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#68]

**Comment by SandGrainOne** [comment]
Gjennomført for eksisterende applikasjonseiere. Oppdatere dokumentasjon for å sikre at det blir gjort for nye applikasjonseiere.

**Comment by bengtfredh** [comment]
Added checkpoint for order reserved nodes to DSB issue. Will be copied to next order. Ref https://github.com/Altinn/altinn-platform/issues/96
