### ISSUE TITLE
Ta i bruk alle 4 agenter i load tester (pipelines) for å få opp nok last.

### ISSUE THREAD

**Issue by annerisbakk** [Altinn/altinn-platform#69]
Når load tester kjører i dag kjøres de kun fra 1 agent. Denne saken går på å utnytte alle 4 agenter til å kjøre tester samt få samlet inn test resultater fra alle testene.

**Comment by aas-tbuar** [comment]
@HenningNormann er denne fremdeles aktuell?

**Comment by HenningNormann** [comment]
@aas-tbuar @SandGrainOne Vet ikke. Dette treffer tester kjørt av andre enn meg - antar K6 tester. Foreløpig har jeg ikke kjørt noen ytelsestester via K6 - har kun brukt Visual Studio og/eller custom tester i C#. @SandGrainOne, hvem er det som kjenner til kjøring via K6 etter at Jeeva sluttet?

**Comment by SandGrainOne** [comment]
Closing until more info has been obtained. Preferably with a concrete example for an actual use case.
