### ISSUE TITLE
Use the new workload identity in platform

### ISSUE THREAD

**Issue by sduranc** [Altinn/altinn-platform#694]
### Description
Enable workload identity i platform clusters.

### Tasks
- [x] Turn on the Workload Identity feature for AKS

**Comment by ootneim** [comment]
@sduranc 
Workload Identity feature is deployed to all AKS platform environments

**Comment by ootneim** [comment]
@sduranc 
What about Eformidling AKS clusters?

**Comment by sduranc** [comment]
> [@sduranc](https://github.com/sduranc) What about Eformidling AKS clusters?

Good point @ootneim, I guess we should enable there as well.

**Comment by ootneim** [comment]
@sduranc I can add WI on the eformidling clusters
