### ISSUE TITLE
 Avklare FREG/ER testdata i YT

### ISSUE THREAD

**Issue by annerisbakk** [Altinn/altinn-platform#70]

**Comment by Herskis** [comment]
Her er jeg :)

**Comment by SandGrainOne** [comment]
Hvem skal gjøre hva i denne saken? @Herskis 
Kanskje "avklaringen" er utført?

**Comment by Herskis** [comment]
Freg data vedlikeholdes en gang i halvåret, ER vedlikeholdes etter behov.

**Comment by Herskis** [comment]
Må bestilles av FA
