### ISSUE TITLE
chore: renew Certificate CN=platform.altinn.no

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#710]
### Description

- [ ] create csr
- [ ] send csr and order to drift@digdir.no
- [ ] package cert with privatekey in a pfx
- [ ] upload pfx to [keyvault](https://portal.azure.com/?feature.msaljs=true#@ai-dev.no/resource/subscriptions/f66298ed-870c-40e0-bb74-6db89c1a364b/resourceGroups/altinn-rg/providers/Microsoft.KeyVault/vaults/altinn-cert-keyvault/overview)

**Comment by Herskis** [comment]
Ligger sammen med andre certificates i sak #736
