### ISSUE TITLE
Tilganger Azure Devops

### ISSUE THREAD

**Issue by rtafj** [Altinn/altinn-platform#716]
### Description

Vi har noen utviklere i Autorisasjonsteamene som trenger tilgang til å utføre deploy og patching.
Gjelder:
Andreas Isnes Nilsen
Marius Thuen
Aleksander Heintz 
Martin Gunnerud
Albert Ohrem Larsen
Alexandra Vedeler
Simen Rekkedal

Trenger du info om hvilke repositories de skal deploye til?

**Comment by Herskis** [comment]
Da har jeg lagt de inn på en litt ny måte (som jeg håper forenkler for fremtiden) og håper det nå fungerer for disse

**Comment by Siri-Anna** [comment]
Albert og Alexandra har fortsatt ikke fått en ai-dev prod-bruker og har dermed ikke tilgang til Azure ressurser for TT02 og Prod for å kunne drifte/vedlikeholde eller feilsøke access-management-frontend som produkt.
De må i det minste ha tilgang til ressursgruppen: accessmanagementui-{env}-rg
samt App Insights for platform. @Herskis
