### ISSUE TITLE
chore: bump platform/eformidling clusters aks v1.27.9

### ISSUE THREAD

**Issue by ootneim** [Altinn/altinn-platform#732]
Upgrade AKS to 1.27.9

- [x] AT21
- [x] AT22
- [x] AT23
- [x] AT24
- [x] YT01
- [x] TT02 (blue/green)
  - [x] TT02 remove old AKS cluster
- [x] PROD (blue/green)
  - [x] PROD remove old AKS cluster
- [x] Eformidling TT02 (blue/green)
  - [x] Eformidling TT02 remove old AKS cluster
- [x] Eformidling PROD (blue/green)
  - [x] Eformidling PROD remove old AKS cluster

**Comment by Herskis** [comment]
Foreløpig blokkert av #740
