### ISSUE TITLE
Azure Subscription for Altinn-Auth Development

### ISSUE THREAD

**Issue by Herskis** [Altinn/altinn-platform#743]
Altinn-Authorization har i dag mesteparten av sin infrastruktur koblet sammen med platform. Tidligere har det vært opprettet tre subscriptions
Altinn-Auth-Prod
Altinn-Auth-Staging
Altinn-Auth-Test
For utvikling så har de benyttet Altinn-Management-Test med begrensninger. Derfor ønskes det opprettet ett eget subscription for authorization hvor de kan ha full contributor rolle. Opprett og tilrettelegg med RBAC subscription:

Altinn-Auth-Dev

**Comment by andreasisnes** [comment]
Et ønske fra Team tilgangsstyring er at det settes opp en app regg per subscription eller tenant med rollen owner eller contributer, helst owner hvis ikke det bryter noen rettninglinjer. Videre så er det ønskelig at det settes opp identity federation for GitHub slik at vi kan deploye IaC fra github. Repoer det er ønskelig at man gjør det for i første omgang er https://github.com/Altinn/altinn-access-management.

Forslag til oppsett. Det må lages credentials per miljø. eksemplet nedenfor viser kun AT22

![Screenshot_2024-04-12-12-48-37](https://github.com/Altinn/altinn-platform/assets/17529876/6e2b0e09-1710-4b3c-9b4b-9db02f791b40)

**Comment by bengtfredh** [comment]
@Herskis I have created an app for github oidc with contributor on subscription Altinn-Auth-Dev. I followed their suggestion for naming.
