### ISSUE TITLE
Service principal used by the APIM deploy pipeline for production has expired crendentials

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-platform#777]
### Description

Team Core needs help updating credentials used by the API Management deployment pipeline for production.

### Additional Information

The failing run:
https://dev.azure.com/brreg/altinn-studio-ops/_build/results?buildId=1029398&view=results

The pipeline definition:
https://dev.azure.com/brreg/_git/altinn-studio-ops?path=/provisioning/altinn_platform/scripts/apim/build/apim-deploy-api.prod.yml

**Comment by bengtfredh** [comment]
For one reason or another I had to recreate the service connection in Azure Devops. Pipeline is running ok now.

**Comment by SandGrainOne** [comment]
Thank you!
