### ISSUE TITLE
Create federated credentials for pull requests in correspondence. 

### ISSUE THREAD

**Issue by Andreass2** [Altinn/altinn-platform#778]
### Description

Team melding/formidling needs federated credentials for pull requests. 

Ref issue #760 < how it was done for main branch. 

Attached file for credentials: 
[credentials-pr.json](https://github.com/Altinn/altinn-platform/files/15307027/credentials-pr.json)

**Comment by Andreass2** [comment]
We will use environments for the CI/CD process. 
The follwing environments will be used: 
- Test
- Staging
- Prod

**Comment by Ceredron** [comment]
We are going to need new federated credentials for use with the correspondence environment.
repo:altinn/altinn-correspondence:environment:test
repo:altinn/altinn-correspondence:environment:staging
repo:altinn/altinn-correspondence:environment:production

Tested that this will also allow us to push from branch as per original issue.

**Comment by bengtfredh** [comment]
done!
