### ISSUE TITLE
Service principals used for dev/test apim deployment are expired

### ISSUE THREAD

**Issue by Ceredron** [Altinn/altinn-platform#780]
### Description

**Description**
Need help updating service principal for APIM deployment.
https://dev.azure.com/brreg/altinn-studio-ops/_build/results?buildId=1029772&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=b95d6380-a28f-54cb-95ac-7cf8f442d632

### Additional Information

Likely same as #777.

(TT02 worked for now)

**Comment by bengtfredh** [comment]
Service connection is updated and pipeline is running ok.
