### ISSUE TITLE
Give Broker prod service principal necessary access

### ISSUE THREAD

**Issue by Ceredron** [Altinn/altinn-platform#789]
**Description**

Broker has three different service principals that are used for deployment. For test, staging and production. The test and staging ones have enough access (Owner + Right to give non-privileged RBAC privileges), but production does not. It needs this because the application deploys storage accounts, and is given access through IaC.
The service principal is called:
Altinn-broker-Prod-github-oidc
Subscription is:
Altinn-Broker-Prod (https://portal.azure.com/#@ai-dev.no/resource/subscriptions/854b0f13-008f-42f1-882d-8813b1af27aa/overview).
For setup in test environment.
https://portal.azure.com/#@ai-dev.no/resource/subscriptions/81cc3a6b-dfdf-49c7-96f0-3efddb159356/users

For RBAC access it needs:
![Image](https://github.com/Altinn/altinn-platform/assets/36594318/2cf29422-61ef-4440-b915-6b40dee773c4)

**Comment by bengtfredh** [comment]
Done!
