### ISSUE TITLE
Ferdigstille kartlegging av Restore scenario

### ISSUE THREAD

**Issue by OddArneSaetervik** [Altinn/altinn-platform#79]
ref https://digdir-digitalisering.atlassian.net/wiki/spaces/T3KP/pages/edit/5049073?draftId=14614529&draftShareId=c5fc47eb-d0fb-4fab-9adf-e902f727cee2&

Ferdigstille Restore scenario seksjonen ift kartlegging av hva vi har og hva vi må få på plass for å støtte dette.

Lage liste over ytterligere avklaringer på infrastruktur som tasker og github issuer til app teamet.

**Comment by ootneim** [comment]
Dette blir en del av Backup og disaster recovery epic: 
https://github.com/Altinn/altinn-platform/issues/441
