### ISSUE TITLE
Limit  Platform/eformidling logging for AKS

### ISSUE THREAD

**Issue by ootneim** [Altinn/altinn-platform#793]
Update the DCR to limit logging from AKS (Platform and Eformidling)

locals {
  interval = tomap({
    at21     = "10m"
    at22     = "10m"
    at23     = "10m"
    at24     = "10m"
    yt01     = "10m"
    tt02     = "10m"
    prod     = "5m"
  })
}

data_sources {
    extension {
      name           = "ContainerInsightsExtension"
      streams        = ["Microsoft-ContainerInsights-Group-Default"]
      extension_name = "ContainerInsights"

      extension_json = jsonencode({
        dataCollectionSettings = {
          interval                 = local.interval[var.environment]
          namespaceFilteringMode   = "Exclude"
          namespaces               = ["kube-system", "gatekeeper-system", "azure-arc"]
          enableContainerLogV2     = true
        }
      })
    }
  }

**Comment by bengtfredh** [comment]
@bengtfredh Check this config compared to apps
