### ISSUE TITLE
Provide an in-cluster configmap with the apim iprange

### ISSUE THREAD

**Issue by Alxandr** [Altinn/altinn-platform#802]
### Description

In order to handle reverse proxies correctly, and be able to generate public facing URLs from within an application running in-cluster (behind APIm), a set of known/trusted proxies is required. For traefik, this is already configured in terraform using:

```yaml
trustedIPs:
- ${data.azurerm_subnet.vnetsubnet.address_prefixes[0]}
```

We need the same ipnetwork known to the application running in-cluster to be able to validate proxy-headers. The simples solution would probably be to create a in-cluster configmap which contains this same value (`${data.azurerm_subnet.vnetsubnet.address_prefixes[0]}`), which applications can then opt in to consume as a environment variable.

**Comment by bengtfredh** [comment]
If we make a configmap like you describe, it will have this content:
```yaml
trustedIPs:
  - 10.211.44.0/22
```
This is what you are looking for?

**Comment by Alxandr** [comment]
As a string? It would be much simpler with just the iprange:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: some-name-goes-here
data:
  apim-network: "10.211.44.0/22"
```

**Comment by bengtfredh** [comment]
https://dev.azure.com/brreg/altinn-studio-ops/_git/altinn-studio-ops/pullrequest/952

**Comment by bengtfredh** [comment]
Deployed in all evironments.
