### ISSUE TITLE
Currently unable to deploy changes to altinn-audit. Expired credentials

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-platform#804]
### Description of the bug

The deploy pipeline for altinn-audit is failing when trying to deploy the changes.

https://dev.azure.com/brreg/altinn-audit/_build/results?buildId=1055425&view=results

### Steps To Reproduce

1. Perform a change to altinn-audit to trigger build and deploy.

**Comment by bengtfredh** [comment]
I have converted service connection to using workload identity federation with openid connect.
You may need to do changes to pipeline, but most likely so will it work.

**Comment by SandGrainOne** [comment]
It's working now. No changes where required. Thank you.
