### ISSUE TITLE
Remove CosmosDB setup and secrets from provisioning scripts

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-platform#805]
### Description

We are no longer using Cosmos DB, and all code related to provisioning, configuring etc. of this service can be removed from our scripts. 

### Tasks

- [x] Delete CosmosDB resources in all environments
- [x] Remove CosmosDB steps in deployment pipelines

_No response_

**Comment by simon-ellefsen** [comment]
Removed in all environments except prod, in case we need the backup
