### ISSUE TITLE
Frist 05.07.2024 | Oppdatere Platform KV for OedAuthzMaskinportenClientSettings--EncodedJWK

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-platform#812]
Ref: https://altinndevops.slack.com/archives/C014H7WPSUB/p1718613118456229

Så trenger autorisasjon å få oppdatert Platform KV Secret: `OedAuthzMaskinportenClientSettings--EncodedJWK` innen 05.07.2024
for alle miljøer.

@jonkjetiloye har laget ny JWK som allerede er registrert på maskinporten klient i både Test og Prod så har ferdige base64 verdier for oppdatering til KV. Ta kontakt med @jonkjetiloye for å få disse når oppdateringen skal gjøres.

**Comment by Herskis** [comment]
@jonkjetiloye Håper Simon ga deg beskjed om at denne var fikset før han tok ferie
