### ISSUE TITLE
Martin Gunnerud mangler rettigheter i Azure til å sjekke "aks workloads"

### ISSUE THREAD

**Issue by annerisbakk** [Altinn/altinn-platform#813]
Får denne feilmeldingen når jeg trykker på disse linkene
{"content":{"error":{"code":"AuthorizationFailed","message":"The client 'ext-mgunn@ai-dev.no' with object id '06892a7a-58bc-4bf1-bc50-acbe82dc3868' does not have authorization to perform action 'Microsoft.ContainerService/managedClusters/read' over scope '/subscriptions/1ab2d164-1861-4ff8-be8c-069c3ee3b70a/resourceGroups/altinnplatform-prod-rg/providers/Microsoft.ContainerService/managedClusters/platform-prod-02-aks' or the scope is invalid. If access was recently granted, please refresh your credentials."}},"headers":{"cache-control":"no-cache","content-length":"502","content-type":"application/json; charset=utf-8","expires":"-1","pragma":"no-cache","x-ms-correlation-request-id":"a1f38b01-4af5-44d2-b44d-5abf83817089","x-ms-failure-cause":"gateway","x-ms-request-id":"a1f38b01-4af5-44d2-b44d-5abf83817089","x-ms-routing-request-id":"SWEDENCENTRAL:20240621T083923Z:a1f38b01-4af5-44d2-b44d-5abf83817089"},"httpStatusCode":403}

Se lenker i deploy-saken: 
https://github.com/Altinn/altinn-authorization/issues/911

**Comment by annerisbakk** [comment]
@Herskis Simen Rekkedal

**Comment by Herskis** [comment]
@annerisbakk Prod ja, skulle jeg egentlig sett en bestilling av prodbruker til Martin...??

**Comment by Herskis** [comment]
@annerisbakk Da har Martin bekreftet at han har tilgang!
