### ISSUE TITLE
Deployment of new secrets for Altinn Notifications

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-platform#815]
### Description

We have [new functionality in Notifications](https://github.com/Altinn/altinn-notifications/issues/548) that requires new secrets in key vault. 

[We have created a PR of the changes we need in Terraform](https://dev.azure.com/brreg/altinn-studio-ops/_git/altinn-studio-ops/pullrequest/962?_a=files)

To begin with we need this deployed to AT, and there is no rush with TT and production, but if we can follow the regular deploy plan that would be great. 

Functionality is for review now, and we will need this in place before code can be deployed to AT.

**Comment by ootneim** [comment]
Deployed to AT and YT01. Deploy to tt02 and prod later this week.
