### ISSUE TITLE
Gerate credentials for studio terraform

### ISSUE THREAD

**Issue by mirkoSekulic** [Altinn/altinn-platform#820]
### Description

Our terraform pipeline in production fails due to expired credentials.

New credentials should be created and updated in the keyvault.

### Additional Information

Credentials used for for studio are stored in altinn-terraform-kv.

**Comment by Herskis** [comment]
Nok en kandidat for federated credentials!?

**Comment by Herskis** [comment]
(https://dev.azure.com/brreg/altinn-studio-ops/_build/results?buildId=1079094&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=d3d2f9a6-97a6-57cb-4647-4151c25603b5)

**Comment by bengtfredh** [comment]
@mirkoSekulic

I can create new token, but we prefer to migrate your serviceconnection to federated credential - for this to work you may need to update pipeline code.

I created new token for now - but please create an issue to upgrade serviceconnection to federated credential.

**Comment by mirkoSekulic** [comment]
@bengtfredh I tried to run the pipeline now but seems like we still have the problem.
I also created the [issue](https://github.com/Altinn/altinn-studio/issues/13081) for moving to federated credentials.
