### ISSUE TITLE
GitHub action template fails if no PR for branch 

### ISSUE THREAD

**Issue by andreasisnes** [Altinn/altinn-platform#828]
### Description

* Update GitHub actions template step `GitHub Issue` so it doesn't fail if there aren't a pull request
* Update GitHub actions template step `Terraform Summary PR` so it doesn't comment on pull request if there aren't any changes

**Comment by tjololo** [comment]
@andreasisnes @bengtfredh this issue seems like it is resolved, can we close this issue?

**Comment by Herskis** [comment]
@andreasisnes Siden stillheten samtykker, så setter vi denne til Done!
