### ISSUE TITLE
Generate certificates for altinn studio

### ISSUE THREAD

**Issue by mirkoSekulic** [Altinn/altinn-platform#834]
### Description

Certificate for *.altinn.studio expires soon (August 7, 2024).
Generate a new certificate and update the value in keyvault.

**Comment by bengtfredh** [comment]
Din sak 2407 1806: "Fornye ssl cert studio.altinn utløper 07.08.2024" er registrert.

**Comment by bengtfredh** [comment]
Certs uploaded to altinn-cert-keyvault
