### ISSUE TITLE
Sertifikatet for platform.altinn.no går ut den 25.05.2022

### ISSUE THREAD

**Issue by annerisbakk** [Altinn/altinn-platform#85]
Sertifikatet for platform.altinn.no går ut 25.05.2022. 

- [x] Bestilling av nytt sertifikat @alt-how
- [x] Opplasting til keyvault @alt-how 
- [ ] Oppdatere platform @ootneim

**Comment by alt-how** [comment]
Sertifikat er bestilt.

**Comment by alt-how** [comment]
Sertifikatet er lastet opp i keyvault. @ootneim
