### ISSUE TITLE
Linkerd: Investigate which metrics do we need

### ISSUE THREAD

**Issue by sduranc** [Altinn/altinn-platform#853]
We're not currently relying on any metrics, so this completely open.

**Comment by monteiro-renato** [comment]
This is a nice start: https://docs.buoyant.io/runbook/monitoring-linkerd/#monitoring-linkerd-control-plane-metrics

**Comment by monteiro-renato** [comment]
The "Linkerd Health" dashboard should help with the metrics/queries to use.
