### ISSUE TITLE
Linkerd: investigate why we are missing metrics

### ISSUE THREAD

**Issue by sduranc** [Altinn/altinn-platform#857]
- It seems that we don't have metrics any more from linkerd
- we changed to export them to the main prometheus some time ago, but maybe something got broken recently

**Comment by monteiro-renato** [comment]
The metrics are being collected but the dashboards are broken (The query I used: `count by (__name__, job)({job=~".*linker.*"})`).
The dashboard queries are filtering on `job="linkerd-proxy"` but the metrics contain `job="linkerd/linkerd-proxy"`.
We can either update the dashboards or configure the jobLabel in the [PodMonitor spec](https://prometheus-operator.dev/docs/api-reference/api/#monitoring.coreos.com/v1.PodMonitorSpec).

**Comment by sduranc** [comment]
Using PodMonitor sounds like the best idea.

**Comment by monteiro-renato** [comment]
Agreed.
Adding a Mutating Webhook to insert the label in every pod seems overkill.
I will close this issue and wait for Bengt to come back to see what is the best approach to tweaking dashboards before uploading them to the new Grafana setup.
