### ISSUE TITLE
Get an overview over number of instances per instanceOwner in production

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-platform#86]
## Description

Load testing conducted has an unrealistic number of Altinn Apps instances per user. 
A load test reflecting a realistic number of instances per user should be conducted to see how the performance of the platform can be expected to behave the next six months. 

Test results will be useful input into what tasks to prioritize and not. 

## Tasks
- [ ] Idenitify which tool to use to retrieve the data
- [ ] Make an anonymized overview of the number of instances per user

**Comment by SandGrainOne** [comment]
Et nytt dataset har blitt identifisert og det er blitt bestilt nye tester basert på dette. 
Det nye settet med brukere har mellom 1 og 5 instanser i stedet for flere tusen som var tilfelle i forrige tester.
