### ISSUE TITLE
Federated credentials for Altinn Correspondence staging/prod

### ISSUE THREAD

**Issue by Ceredron** [Altinn/altinn-platform#877]
### Description

Ref: https://github.com/Altinn/altinn-platform/issues/778

We previously got federated credentials generated for the Github environment "test". We now need it for the Github environments 'staging' and 'prod'. Subjects:

repo:Altinn/altinn-correspondence:environment:staging
repo:Altinn/altinn-correspondence:environment:production

### Additional Information

Service principals already exist (e.g altinn-broker-Staging-github-oidc). I think federated credentials were set up at the same time in staging and production too, but we get an error on deploy. Case sensitivity may be an issue. Ref error:

`AADSTS700213: No matching federated identity record found for presented assertion subject 'repo:Altinn/altinn-correspondence:environment:staging'. Please note that the matching is done using a case-sensitive comparison. Check your federated identity credential Subject, Audience and Issuer against the presented assertion. https://learn.microsoft.com/entra/workload-id/workload-identity-federation Trace ID: 587bf223-a615-4613-9073-8f63e8e73800 Correlation ID: a11c5d2e-84c7-4b0a-99ed-d97d22a3bba6 Timestamp: 2024-08-20 13:49:47ZShow more`
https://github.com/Altinn/altinn-correspondence/actions/runs/10470572666

**Comment by tjololo** [comment]
I have checked the service principal for altinn-correspondence staging up against test and the federated identities are setup the same way and should be fine as far as I can see.
Is there any possibility that the clientID is wrong in the pipeline? eg. it is defined as a repo secret and not a environment secret, or wrong in the staging environment?

**Comment by tjololo** [comment]
The issue seems to be resolved. Closing the issue
