### ISSUE TITLE
Certificate for Team Authorization

### ISSUE THREAD

**Issue by andreasisnes** [Altinn/altinn-platform#927]
### Description

We are creating new infrastructure for team authorization and want to hide public facing services behind a specific domain. Thus, we need a certificate for services developed by authorization. Proposed subdomain `auth.api.at21.altinn.cloud`

**Comment by bengtfredh** [comment]
Created a 180 day cert for testing:
Uploaded to key vault “altinn-cert-keyvault” secret named “auth-api-at21-altinn-cloud”
