### ISSUE TITLE
Move BMS from old Slack to New

### ISSUE THREAD

**Issue by Herskis** [Altinn/altinn-platform#934]
Altinn 3 BMS is yet toi be moved from old slack to new #altinn-alerts-prod

Some investigation has been done, and there seems to be a lack of ownership to the code

https://dev.azure.com/brreg/altinn-studio/_dashboards/dashboard/fa0678ad-960d-4307-aba2-ba29c9804c9d

**Comment by borgethommesen** [comment]
Changed notifications receiver from the Altinn DevOps channels to the Digitaliseringsdirektoratet channels email addresses used for integrations.
