### ISSUE TITLE
Authorization certificates

### ISSUE THREAD

**Issue by howieandersen** [Altinn/altinn-platform#942]
### Description

I forbindelse med ny infrastruktur for team Autorisering, trenger vi sertifikater for følgende domener:

Backend:
- AT22: api.auth.at22.altinn.cloud
- AT23: api.auth.at23.altinn.cloud
- AT24: api.auth.at24.altinn.cloud
- YT02: api.auth.yt02.altinn.cloud
- TT02: api.auth.tt02.altinn.no
- PROD: api.auth.altinn.no

Frontend:
- AT22: auth.at22.altinn.cloud
- AT23: auth.at23.altinn.cloud
- AT24: auth.at24.altinn.cloud
- YT02: auth.yt02.altinn.cloud
- TT02: auth.tt02.altinn.no
- PROD: auth.altinn.no

**Comment by howieandersen** [comment]
@andreasisnes @jonkjetiloye

**Comment by bengtfredh** [comment]
I think we can combine som of the certs:
1 cert with: at21, at22, at23, at24, yt01
1 cert for: tt02
1 cert for: prod

We can combine backend and fronten in same cert. Or have separate. What are your thoughts?

**Comment by andreasisnes** [comment]
updated the issue like you suggested @bengtfredh

**Comment by bengtfredh** [comment]
Order ticket 2409 3432

**Comment by bengtfredh** [comment]
cert uploaded to keyvault
