### ISSUE TITLE
New Azure Database for PostgreSQL flexible servers resource for the Profile application, Team Core

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-platform#944]
### Description

Team Core needs help provisioning new instances of the Azure Database for PostgreSQL flexible servers resource to be used by the Profile application. We will need the new resource in all environments.

- New Azure Database for PostgreSQL flexible servers resource for Profile
- New database called `profiledb`.
- New schema with the name 'krr' 
- New login called `platform_profile_admin`
- New login called 'platform_profile'
- Do not include the cron extension

We're also wondering if defining schemas in terraform is required or if we can define those through SQL operations.

**Comment by SandGrainOne** [comment]
Tested okay in AT21. I did some manual testing using the two logins. Works the way I expect it to. Please proceed with deployment.

**Comment by simon-ellefsen** [comment]
Deployed to all environments
