### ISSUE TITLE
Move the monitoring related resources from the AKS module to it's own module

### ISSUE THREAD

**Issue by monteiro-renato** [Altinn/altinn-platform#953]
We would like to deploy the new monitoring setup (the one being used for the apps clusters) in the platform clusters by referencing a module. However, this is currently not possible since the monitoring related resources are being created in the [apps AKS module](https://dev.azure.com/brreg/altinn-apps-ops/_git/terraform-modules?path=/modules/aks).

The goal of this task is to separate the monitoring related resources from the apps aks module into it's own module. This will then allow us to reference the monitoring module from the platform infrastructure repo and deploy the new monitoring setup together with the existing platform k8s module.

**Comment by monteiro-renato** [comment]
PR: https://dev.azure.com/brreg/altinn-apps-ops/_git/terraform-modules/pullrequest/1067

**Comment by khanrn** [comment]
Moved monitoring to a separate module! Deployed to AT and TT environment so far! Will do to prod next week!

**Comment by monteiro-renato** [comment]
The monitoring related components have been pulled out but we can't deploy this module in the platform clusters yet.
The module has [dependencies on the platform clusters](https://dev.azure.com/brreg/altinn-apps-ops/_git/terraform-modules?path=/modules/monitoring/variables.tf&version=GBmaster&line=52&lineEnd=56&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents). This seems to be outdated but I didn't want to remove it without a deeper analysis.

**Comment by monteiro-renato** [comment]
> The monitoring related components have been pulled out but we can't deploy this module in the platform clusters yet. The module has [dependencies on the platform clusters](https://dev.azure.com/brreg/altinn-apps-ops/_git/terraform-modules?path=/modules/monitoring/variables.tf&version=GBmaster&line=52&lineEnd=56&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents). This seems to be outdated but I didn't want to remove it without a deeper analysis.

Removed here > https://dev.azure.com/brreg/altinn-apps-ops/_git/terraform-modules/pullrequest/1170
