### ISSUE TITLE
Fornyelse av sertifikater for Altinn 2

### ISSUE THREAD

**Issue by jvsimo** [Altinn/altinn-platform#961]
Vi trenger å fornye de to eksisterende sertifikatene:

- [x] *.altinn.no
- [x] altinn.no med SAN www.altinn.no. 
- [x] Sertifikatene kan sendes til Anders Mørland Aabech <anders.aabech@basefarm-orange.com>

**Comment by Herskis** [comment]
Setter denne til @bengt som avtalt på Slack

**Comment by bengtfredh** [comment]
Cert ordered in ticket #2409 3432
