### ISSUE TITLE
Team Core needs help setting up some namespaces in k8 for some of their applications

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-platform#968]
### Description

Team core will now update their application deploy of a few applications to have them moved out of the default namespace. We're going to need your help to make 2 secrets available for the applications at their new home.

namespace:
- profile - To be used by the Profile application. 
- studio - To be used by Receipt, Storage and PDF.
- notifications - To be used by the Notifications applications
- events - To be used by the Events application(s)

Both of these namespaces needs access to the following secrets
- `altinn-appsettings-secret`
- `accesstoken`

We would also like to know if there are other elements with namespaces to consider.

**Comment by ootneim** [comment]
Part of tag.1.7.96

PR with changes: https://dev.azure.com/brreg/altinn-studio-ops/_git/altinn-studio-ops/pullrequest/1074?_a=files

**Comment by ootneim** [comment]
@SandGrainOne Namespaces in this issue have been created with secrets in all AT environments and YT01.

**Comment by SandGrainOne** [comment]
Talked to Bengt and we believe changing namespace will require some downtime unless we use blue-green. It's not going to be possible to have the same application in both namespaces because or routing. We would need a window where the applications are uninstalled before they're installed again in new namespace.

Unless we find a workaround for this the idea is to update more applications in one go instead of taking them one by one.
