### ISSUE TITLE
Copy Timescale data to new table for Auditlog

### ISSUE THREAD

**Issue by ootneim** [Altinn/altinn-platform#983]
Copy data from Timescale to a new Table for Auditlog

Procedure is located here: https://github.com/Altinn/altinn-platform/issues/906

Performed in

- [x] AT21
- [x] AT22
- [x] AT23
- [x] AT24
- [x] YT01
- [x] TT02
- [x] PROD

SQL Commands:

```postgresql
CREATE TABLE authentication.eventlogv0 (LIKE authentication.eventlog INCLUDING ALL);

INSERT INTO authentication.eventlogv0
SELECT * FROM authentication.eventlog;

CREATE INDEX authentication_eventlogv0_created_idx ON authentication.eventlogv0 (created);
```

```postgresql
CREATE TABLE authz.eventlogv0 (LIKE authz.eventlog INCLUDING ALL);

INSERT INTO authz.eventlogv0
SELECT * FROM authz.eventlog;

CREATE INDEX authz_eventlogv0_created_idx ON authz.eventlogv0 (created);
```

**Comment by acn-dgopa** [comment]
We have now decided to remove the use of timescaledb from the auditlog database. A background service part of auditlog application will create necessary partitions automatically. It will use the native postgres partition and it will be a new table. 
The existing data on the table that uses timescale partitioning should be migrated to a new table without timescale. This will be done by the infra team.
