### ISSUE TITLE
Deploy Pyrra in the apps clusters

### ISSUE THREAD

**Issue by monteiro-renato** [Altinn/altinn-platform#995]
Now that we can push metrics from the various service owner environments into the centralized observability environment, we can start thinking about which metrics we need. SLO metrics are an easy choice so we should deploy Pyrra and re-use some of the SLOs already implemented in the platform clusters such as the Traefik ones. Afterwards, we can create a Dashboard to provide us with an overview of the various cluster in a single place.

**Comment by monteiro-renato** [comment]
PR: https://dev.azure.com/brreg/altinn-apps-ops/_git/terraform-modules/pullrequest/1100

**Comment by khanrn** [comment]
Deployed to all AT, TT and PROD!
