### ISSUE TITLE
Deploy Traefik SLO similar to the one defined in the platform clusters

### ISSUE THREAD

**Issue by monteiro-renato** [Altinn/altinn-platform#996]
Continuation of https://github.com/Altinn/altinn-platform/issues/995

**Comment by monteiro-renato** [comment]
PR: https://dev.azure.com/brreg/altinn-apps-ops/_git/terraform-modules/pullrequest/1100

**Comment by khanrn** [comment]
Deployed to all AT, TT and PROD
